import type { TelemetrySnapshot } from "./telemetry-snapshot";

export type MockSessionScenario = "practice" | "qualifying" | "race";
export type MockLocationScenario = "track" | "pits";
export type MockDataState = "ready" | "stale" | "disconnected" | "error";

const MOCK_CAPTURED_AT = 1_720_569_600_000;

const SESSION_REMAINING_SECONDS: Record<MockSessionScenario, number> = {
  practice: 5328,
  qualifying: 900,
  race: 3600,
};

const CANONICAL_SCORING: readonly Record<string, unknown>[] = [
  {
    id: 0,
    driverNumber: "36",
    driverName: "ALPINE",
    teamName: "ALPINE",
    vehicleClass: "HYPERCAR",
    place: 1,
    isPlayer: false,
    inPits: false,
    bestLapTime: 89.823,
    lastLapTime: 90.412,
    totalLaps: 34,
  },
  {
    id: 1,
    driverNumber: "5",
    driverName: "PORSCHE PENSKE",
    teamName: "PORSCHE PENSKE",
    vehicleClass: "HYPERCAR",
    place: 2,
    isPlayer: false,
    inPits: false,
    bestLapTime: 90.101,
    lastLapTime: 91.004,
    totalLaps: 34,
  },
  {
    id: 2,
    driverNumber: "51",
    driverName: "FERRARI AF",
    teamName: "FERRARI AF",
    vehicleClass: "HYPERCAR",
    place: 3,
    isPlayer: false,
    inPits: false,
    bestLapTime: 89.455,
    lastLapTime: 90.332,
    totalLaps: 34,
  },
  {
    id: 3,
    driverNumber: "2",
    driverName: "CADILLAC RACING",
    teamName: "CADILLAC RACING",
    vehicleClass: "HYPERCAR",
    place: 4,
    isPlayer: false,
    inPits: false,
    bestLapTime: 91.234,
    lastLapTime: 92.001,
    totalLaps: 34,
  },
  {
    id: 4,
    driverNumber: "8",
    driverName: "TOYOTA GAZOO",
    teamName: "TOYOTA GAZOO",
    vehicleClass: "HYPERCAR",
    place: 5,
    isPlayer: true,
    inPits: false,
    bestLapTime: 90.876,
    lastLapTime: 91.221,
    totalLaps: 34,
  },
  {
    id: 5,
    driverNumber: "94",
    driverName: "PEUGEOT",
    teamName: "PEUGEOT",
    vehicleClass: "HYPERCAR",
    place: 6,
    isPlayer: false,
    inPits: false,
    bestLapTime: 92.110,
    lastLapTime: 93.221,
    totalLaps: 34,
  },
  {
    id: 6,
    driverNumber: "83",
    driverName: "AF CORSE",
    teamName: "AF CORSE",
    vehicleClass: "HYPERCAR",
    place: 7,
    isPlayer: false,
    inPits: false,
    bestLapTime: 92.445,
    lastLapTime: 93.018,
    totalLaps: 34,
  },
  {
    id: 7,
    driverNumber: "12",
    driverName: "HERTZ TEAM JOTA",
    teamName: "HERTZ TEAM JOTA",
    vehicleClass: "HYPERCAR",
    place: 8,
    isPlayer: false,
    inPits: false,
    bestLapTime: 91.789,
    lastLapTime: 92.554,
    totalLaps: 34,
  },
  {
    id: 8,
    driverNumber: "20",
    driverName: "BMW M TEAM",
    teamName: "BMW M TEAM",
    vehicleClass: "HYPERCAR",
    place: 9,
    isPlayer: false,
    inPits: false,
    bestLapTime: 93.0,
    lastLapTime: 94.102,
    totalLaps: 34,
  },
  {
    id: 9,
    driverNumber: "63",
    driverName: "LAMBORGHINI",
    teamName: "LAMBORGHINI",
    vehicleClass: "HYPERCAR",
    place: 10,
    isPlayer: false,
    inPits: true,
    bestLapTime: 93.567,
    lastLapTime: 95.004,
    totalLaps: 33,
  },
  {
    id: 10,
    driverNumber: "11",
    driverName: "ISOTTA FRASCHINI",
    teamName: "ISOTTA FRASCHINI",
    vehicleClass: "HYPERCAR",
    place: 11,
    isPlayer: false,
    inPits: false,
    bestLapTime: 94.200,
    lastLapTime: 95.320,
    totalLaps: 34,
  },
  {
    id: 11,
    driverNumber: "99",
    driverName: "PROTON COMP",
    teamName: "PROTON COMP",
    vehicleClass: "HYPERCAR",
    place: 12,
    isPlayer: false,
    inPits: false,
    bestLapTime: 94.880,
    lastLapTime: 96.102,
    totalLaps: 34,
  },
  {
    id: 12,
    driverNumber: "22",
    driverName: "UNITED AUTOSPORTS",
    teamName: "UNITED AUTOSPORTS",
    vehicleClass: "HYPERCAR",
    place: 13,
    isPlayer: false,
    inPits: false,
    bestLapTime: 95.123,
    lastLapTime: 96.441,
    totalLaps: 34,
  },
  {
    id: 13,
    driverNumber: "34",
    driverName: "INTER EUROPOL",
    teamName: "INTER EUROPOL",
    vehicleClass: "HYPERCAR",
    place: 14,
    isPlayer: false,
    inPits: false,
    bestLapTime: 96.456,
    lastLapTime: 97.012,
    totalLaps: 34,
  },
  {
    id: 14,
    driverNumber: "7",
    driverName: "LIGIER JSP320",
    teamName: "LIGIER JSP320",
    vehicleClass: "HYPERCAR",
    place: 15,
    isPlayer: false,
    inPits: false,
    bestLapTime: 102.5,
    lastLapTime: 103.212,
    totalLaps: 33,
  },
  {
    id: 15,
    driverNumber: "86",
    driverName: "GR RACING",
    teamName: "GR RACING",
    vehicleClass: "HYPERCAR",
    place: 16,
    isPlayer: false,
    inPits: false,
    bestLapTime: 108.2,
    lastLapTime: 109.334,
    totalLaps: 33,
  },
  {
    id: 16,
    driverNumber: "55",
    driverName: "MAZDA",
    teamName: "MAZDA",
    vehicleClass: "HYPERCAR",
    place: 17,
    isPlayer: false,
    inPits: false,
    bestLapTime: 109.8,
    lastLapTime: 110.5,
    totalLaps: 33,
  },
  {
    id: 17,
    driverNumber: "23",
    driverName: "NISSAN",
    teamName: "NISSAN",
    vehicleClass: "HYPERCAR",
    place: 18,
    isPlayer: false,
    inPits: false,
    bestLapTime: 111.2,
    lastLapTime: 112.0,
    totalLaps: 33,
  },
  {
    id: 18,
    driverNumber: "98",
    driverName: "ASTON MARTIN",
    teamName: "ASTON MARTIN",
    vehicleClass: "HYPERCAR",
    place: 19,
    isPlayer: false,
    inPits: false,
    bestLapTime: 113.0,
    lastLapTime: 114.2,
    totalLaps: 32,
  },
  {
    id: 19,
    driverNumber: "59",
    driverName: "MCLAREN",
    teamName: "MCLAREN",
    vehicleClass: "HYPERCAR",
    place: 20,
    isPlayer: false,
    inPits: false,
    bestLapTime: 115.5,
    lastLapTime: 116.8,
    totalLaps: 32,
  },
  // LMP2 class (places 21-25): multiclass support for relative and multiclass-relative testing
  {
    id: 20,
    driverNumber: "1",
    driverName: "ORECA LMP2",
    teamName: "ORECA TEAM",
    vehicleClass: "LMP2",
    place: 21,
    isPlayer: false,
    inPits: false,
    bestLapTime: 105.2,
    lastLapTime: 106.1,
    totalLaps: 32,
  },
  {
    id: 21,
    driverNumber: "2",
    driverName: "DALLARA LMP2",
    teamName: "DALLARA TEAM",
    vehicleClass: "LMP2",
    place: 22,
    isPlayer: false,
    inPits: false,
    bestLapTime: 106.0,
    lastLapTime: 107.2,
    totalLaps: 32,
  },
  {
    id: 22,
    driverNumber: "3",
    driverName: "BR LMP2",
    teamName: "BR RACING",
    vehicleClass: "LMP2",
    place: 23,
    isPlayer: false,
    inPits: false,
    bestLapTime: 107.1,
    lastLapTime: 108.3,
    totalLaps: 32,
  },
  {
    id: 23,
    driverNumber: "4",
    driverName: "LIGIER LMP2",
    teamName: "LIGIER LMP2",
    vehicleClass: "LMP2",
    place: 24,
    isPlayer: false,
    inPits: false,
    bestLapTime: 107.8,
    lastLapTime: 109.0,
    totalLaps: 31,
  },
  {
    id: 24,
    driverNumber: "5",
    driverName: "ORECA PRO",
    teamName: "PRO TEAM",
    vehicleClass: "LMP2",
    place: 25,
    isPlayer: false,
    inPits: false,
    bestLapTime: 108.5,
    lastLapTime: 110.2,
    totalLaps: 31,
  },
  // LMGT3 class (places 26-30): multiclass support for multiclass-aware overlays
  {
    id: 25,
    driverNumber: "10",
    driverName: "BMW LMGT3",
    teamName: "BMW GT TEAM",
    vehicleClass: "LMGT3",
    place: 26,
    isPlayer: false,
    inPits: false,
    bestLapTime: 118.2,
    lastLapTime: 119.5,
    totalLaps: 31,
  },
  {
    id: 26,
    driverNumber: "11",
    driverName: "PORSCHE GT3",
    teamName: "PORSCHE GT",
    vehicleClass: "LMGT3",
    place: 27,
    isPlayer: false,
    inPits: false,
    bestLapTime: 119.1,
    lastLapTime: 120.8,
    totalLaps: 31,
  },
  {
    id: 27,
    driverNumber: "12",
    driverName: "CORVETTE GT3",
    teamName: "CORVETTE GT",
    vehicleClass: "LMGT3",
    place: 28,
    isPlayer: false,
    inPits: false,
    bestLapTime: 120.0,
    lastLapTime: 121.7,
    totalLaps: 30,
  },
  {
    id: 28,
    driverNumber: "13",
    driverName: "FERRARI GT3",
    teamName: "FERRARI GT",
    vehicleClass: "LMGT3",
    place: 29,
    isPlayer: false,
    inPits: false,
    bestLapTime: 120.8,
    lastLapTime: 122.5,
    totalLaps: 30,
  },
  {
    id: 29,
    driverNumber: "14",
    driverName: "LAMBORGHINI GT",
    teamName: "LAMBORGHINI GT",
    vehicleClass: "LMGT3",
    place: 30,
    isPlayer: false,
    inPits: false,
    bestLapTime: 121.5,
    lastLapTime: 123.2,
    totalLaps: 30,
  },
];

function buildReadyPlayer(location: MockLocationScenario) {
  return {
    inPit: location === "pits",
    deltaSeconds: -0.15,
    lastLapSeconds: 91.221,
    bestLapSeconds: 90.876,
    throttle: 0.78,
    brake: 0.12,
    clutch: 0,
    speedKph: 242,
    rpm: 8120,
    gear: 6,
    fuelLiters: 58.4,
    totalLaps: 14,
  };
}

export function buildMockTelemetry(input: {
  session: MockSessionScenario;
  location: MockLocationScenario;
  state?: MockDataState;
}): TelemetrySnapshot {
  const state = input.state ?? "ready";
  const base: TelemetrySnapshot = {
    status: state === "ready" ? "ready" : state,
    capturedAt: MOCK_CAPTURED_AT,
    session: {
      type: input.session,
      remainingSeconds: SESSION_REMAINING_SECONDS[input.session],
      globalFlag: "green",
      sectorFlags: ["green", "green", "green"],
    },
    player: buildReadyPlayer(input.location),
    scoring: CANONICAL_SCORING.map((entry) => ({ ...entry })),
  };

  if (state === "disconnected") {
    return {
      ...base,
      status: "disconnected",
      player: { inPit: false },
      scoring: [],
    };
  }

  if (state === "error") {
    return {
      ...base,
      status: "error",
      errorMessage: "mock telemetry error",
      player: { inPit: false },
      scoring: [],
    };
  }

  if (state === "stale") {
    return {
      ...base,
      status: "stale",
    };
  }

  return base;
}
