import type { Calendar } from "../calendar/calendar-types";

/**
 * Mock LMU calendar data for the visual harness.
 * Dates are around 2026-07-03 (Friday) to match the current date.
 */
export const mockCalendar: Calendar = {
  version: 1,
  timezone: "UTC",
  reminderMinutes: [30, 15, 10, 5, 2],
  followedEventIds: [],
  followedSeriesIds: [],
  updated: "2026-07-03T10:00:00Z",
  events: [
    {
      id: "ev-special-1",
      title: "Carrera Especial Bronce",
      sim: "lmu",
      track: "Monza",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-03T18:00:00Z",
      durationMin: 45,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-special-2",
      title: "Carrera Especial Plata",
      sim: "lmu",
      track: "Spa",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-03T19:30:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-special-3",
      title: "Carrera Especial Oro",
      sim: "lmu",
      track: "Le Mans",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-03T21:00:00Z",
      durationMin: 90,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // Extra LMU events on July 3 to make the DayView screenshot denser
    {
      id: "ev-jul3-1",
      title: "LMU - Free Practice",
      sim: "lmu",
      track: "Monza",
      series: "series-special",
      sessionLabel: "Practice",
      startTime: "2026-07-03T12:00:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-jul3-2",
      title: "LMU - WEC Practice 1",
      sim: "lmu",
      track: "Spa",
      series: "series-special",
      sessionLabel: "Practice",
      startTime: "2026-07-03T13:30:00Z",
      durationMin: 90,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-jul3-3",
      title: "LMU - WEC Free Practice 2",
      sim: "lmu",
      track: "Le Mans",
      series: "series-special",
      sessionLabel: "Practice",
      startTime: "2026-07-03T15:00:00Z",
      durationMin: 90,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-jul3-4",
      title: "LMU - WEC Sprint",
      sim: "lmu",
      track: "Portimao",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-03T17:00:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-jul3-5",
      title: "LMU - Qualifying",
      sim: "lmu",
      track: "Silverstone",
      series: "series-special",
      sessionLabel: "Qualifying",
      startTime: "2026-07-03T18:00:00Z",
      durationMin: 30,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-special-4",
      title: "Carrera Especial Ayer",
      sim: "lmu",
      track: "Silverstone",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-02T19:00:00Z",
      durationMin: 45,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 6 (Monday) – multiple concrete events to exercise the month grid
    {
      id: "ev-mon-1",
      title: "LMU - WEC Sprint",
      sim: "lmu",
      track: "Monza",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-06T14:00:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-mon-2",
      title: "LMU - GT3 Open",
      sim: "lmu",
      track: "Spa",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-06T16:00:00Z",
      durationMin: 45,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-mon-3",
      title: "LMU - Free Practice",
      sim: "lmu",
      track: "Le Mans",
      series: "series-special",
      sessionLabel: "Practice",
      startTime: "2026-07-06T18:00:00Z",
      durationMin: 90,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 8 (Wednesday)
    {
      id: "ev-wed-1",
      title: "LMU - Endurance Night",
      sim: "lmu",
      track: "Sebring",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-08T19:00:00Z",
      durationMin: 120,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 10 (Friday)
    {
      id: "ev-fri-1",
      title: "LMU - Qualifying",
      sim: "lmu",
      track: "Portimao",
      series: "series-special",
      sessionLabel: "Qualifying",
      startTime: "2026-07-10T17:00:00Z",
      durationMin: 30,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 12 (Sunday)
    {
      id: "ev-sun-1",
      title: "LMU - Sunday Special",
      sim: "lmu",
      track: "Nürburgring",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-12T20:00:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 15 (Wednesday) – exercises the "today" cell in the harness
    {
      id: "ev-today-1",
      title: "LMU - Midweek Race",
      sim: "lmu",
      track: "Imola",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-15T18:00:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 18 (Saturday)
    {
      id: "ev-sat-1",
      title: "LMU - Sprint Saturday",
      sim: "lmu",
      track: "COTA",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-18T15:00:00Z",
      durationMin: 45,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 24 (Friday)
    {
      id: "ev-fri-2",
      title: "LMU - 24h Warmup",
      sim: "lmu",
      track: "Le Mans",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-24T20:00:00Z",
      durationMin: 90,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    // July 31 (Friday)
    {
      id: "ev-fri-3",
      title: "LMU - Season Finale",
      sim: "lmu",
      track: "Monza",
      series: "series-special",
      sessionLabel: "Race",
      startTime: "2026-07-31T18:00:00Z",
      durationMin: 60,
      registrationUrl: "",
      source: "",
      notes: "",
    },
  ],
  series: [
    {
      id: "series-bronce",
      name: "LMU Fixed Bronce",
      tier: "beginner",
      licenseLabel: "Rookie",
      track: "Monza",
      vehicleClass: "GT3",
      setup: "Fixed",
      durationMin: 20,
      splits: 0,
      assists: "",
      tyreWarmers: false,
      tyres: 0,
      recurrence: { kind: "interval", intervalMinutes: 15 },
    },
    {
      id: "series-plata",
      name: "LMU Fixed Plata",
      tier: "intermediate",
      licenseLabel: "Silver",
      track: "Spa",
      vehicleClass: "LMP2",
      setup: "Fixed",
      durationMin: 20,
      splits: 0,
      assists: "",
      tyreWarmers: false,
      tyres: 0,
      recurrence: { kind: "interval", intervalMinutes: 20 },
    },
    {
      id: "series-oro",
      name: "LMU Fixed Oro",
      tier: "advanced",
      licenseLabel: "Gold",
      track: "Le Mans",
      vehicleClass: "Hypercar",
      setup: "Open",
      durationMin: 30,
      splits: 0,
      assists: "",
      tyreWarmers: false,
      tyres: 0,
      recurrence: { kind: "interval", intervalMinutes: 30 },
    },
    {
      id: "series-special",
      name: "LMU Special Events",
      tier: "special",
      licenseLabel: "All",
      track: "Variado",
      vehicleClass: "Mixed",
      setup: "Open",
      durationMin: 45,
      splits: 0,
      assists: "",
      tyreWarmers: false,
      tyres: 0,
      recurrence: { kind: "weekly-slots", days: [], timesUTC: [] },
    },
    {
      id: "series-weekly",
      name: "WEC Weekly",
      tier: "weekly",
      licenseLabel: "All",
      track: "Portimao",
      vehicleClass: "Hypercar & LMGT3",
      setup: "Open",
      durationMin: 100,
      splits: 0,
      assists: "",
      tyreWarmers: false,
      tyres: 0,
      recurrence: {
        kind: "weekly-slots",
        days: ["Thu", "Fri", "Sun"],
        timesUTC: ["21:00"],
      },
    },
  ],
  seriesPreviews: [
    {
      seriesId: "series-bronce",
      scheduleLabel: "Cada 15 min",
      nextStarts: ["2026-07-03T18:00:00Z", "2026-07-03T18:15:00Z"],
    },
    {
      seriesId: "series-plata",
      scheduleLabel: "Cada 20 min",
      nextStarts: ["2026-07-03T19:30:00Z", "2026-07-03T19:50:00Z"],
    },
    {
      seriesId: "series-oro",
      scheduleLabel: "Cada 30 min",
      nextStarts: ["2026-07-03T21:00:00Z", "2026-07-03T21:30:00Z"],
    },
    {
      seriesId: "series-special",
      scheduleLabel: "Eventos Especiales",
      nextStarts: ["2026-07-03T18:00:00Z", "2026-07-03T19:30:00Z", "2026-07-03T21:00:00Z"],
    },
    {
      seriesId: "series-weekly",
      scheduleLabel: "Jueves/Domingo 21:00",
      nextStarts: ["2026-07-05T21:00:00Z"],
    },
  ],
};
