import type { Calendar } from "../calendar/calendar-types";

/**
 * Mock LMU official calendar (UTC) for the visual harness and tests.
 * Mirrors the real bundled schedule (internal/calendar/seed/lmu-weekly-schedule.json)
 * plus concrete special events, so the calendar shows cadence + preparation
 * details instead of materialised hourly blocks.
 */
export const mockCalendar: Calendar = {
  version: 1,
  timezone: "UTC",
  reminderMinutes: [30, 15, 10, 5, 2],
  followedEventIds: [],
  followedSeriesIds: [],
  updated: "2026-07-07T10:00:00Z",
  events: [
    {
      id: "ev-special-imola-4h-1",
      title: "ELMS 4 Hours of Imola",
      sim: "lmu",
      track: "Imola (ELMS)",
      series: "series-special-imola",
      sessionLabel: "Race",
      startTime: "2026-07-10T03:00:00Z",
      durationMin: 240,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-special-imola-4h-2",
      title: "ELMS 4 Hours of Imola",
      sim: "lmu",
      track: "Imola (ELMS)",
      series: "series-special-imola",
      sessionLabel: "Race",
      startTime: "2026-07-11T08:00:00Z",
      durationMin: 240,
      registrationUrl: "",
      source: "",
      notes: "",
    },
    {
      id: "ev-special-imola-4h-3",
      title: "ELMS 4 Hours of Imola",
      sim: "lmu",
      track: "Imola (ELMS)",
      series: "series-special-imola",
      sessionLabel: "Race",
      startTime: "2026-07-12T13:00:00Z",
      durationMin: 240,
      registrationUrl: "",
      source: "",
      notes: "",
    },
  ],
  series: [
    // ── Beginner (Bronze SR): every 15 min, 20m races, 20 splits ──
    {
      id: "beginner-lmgt3-fixed",
      name: "LMGT3 Fixed",
      tier: "beginner",
      licenseLabel: "Bronze SR",
      track: "Sebring (School)",
      vehicleClass: "LMGT3 Class",
      setup: "Fixed",
      durationMin: 20,
      raceDurationMin: 20,
      eventDurationMin: 31,
      startOffsetMinute: 15,
      splits: 20,
      assists: "High assists allowed",
      tyreWarmers: true,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 15 },
    },
    {
      id: "beginner-mclaren-challenge",
      name: "Logitech McLaren G Challenge Q5",
      tier: "beginner",
      licenseLabel: "Bronze SR",
      track: "Monza (WEC)",
      vehicleClass: "McLaren 720S LMGT3",
      setup: "Fixed",
      durationMin: 20,
      raceDurationMin: 20,
      eventDurationMin: 31,
      startOffsetMinute: 30,
      splits: 20,
      assists: "High assists allowed",
      tyreWarmers: true,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 15 },
    },
    {
      id: "beginner-lmp3-fixed",
      name: "LMP3 Fixed",
      tier: "beginner",
      licenseLabel: "Bronze SR",
      track: "Fuji (Classic)",
      vehicleClass: "LMP3 Class",
      setup: "Fixed",
      durationMin: 20,
      raceDurationMin: 20,
      eventDurationMin: 31,
      startOffsetMinute: 45,
      splits: 20,
      assists: "High assists allowed",
      tyreWarmers: true,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 15 },
    },
    // ── Intermediate (Silver SR): every 20 min, 30m races, 38 splits ──
    {
      id: "intermediate-lmgt3-sprint",
      name: "LMGT3 Sprint Cup",
      tier: "intermediate",
      licenseLabel: "Silver SR",
      track: "COTA (National)",
      vehicleClass: "LMGT3 Class",
      setup: "Open",
      durationMin: 30,
      raceDurationMin: 30,
      eventDurationMin: 41,
      startOffsetMinute: 15,
      splits: 38,
      assists: "Low assists allowed",
      tyreWarmers: false,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 20 },
    },
    {
      id: "intermediate-prototype-fixed",
      name: "Prototype Fixed",
      tier: "intermediate",
      licenseLabel: "Silver SR",
      track: "Barcelona (ELMS)",
      vehicleClass: "LMP2 (ELMS) & LMP3 Classes",
      setup: "Fixed",
      durationMin: 30,
      raceDurationMin: 30,
      eventDurationMin: 41,
      startOffsetMinute: 30,
      splits: 38,
      assists: "Low assists allowed",
      tyreWarmers: false,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 20 },
    },
    {
      id: "intermediate-elms-sprint",
      name: "ELMS Sprint Trophy",
      tier: "intermediate",
      licenseLabel: "Silver SR",
      track: "Portimao (WEC)",
      vehicleClass: "LMP2 (ELMS), LMP3 & LMGT3 Classes",
      setup: "Open",
      durationMin: 30,
      raceDurationMin: 30,
      eventDurationMin: 41,
      startOffsetMinute: 45,
      splits: 38,
      assists: "Low assists allowed",
      tyreWarmers: false,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 20 },
    },
    // ── Advanced (Gold SR): every 30 min, 38-60m races ──
    {
      id: "advanced-one-stint-sprint",
      name: "One Stint Sprint",
      tier: "advanced",
      licenseLabel: "Gold SR",
      track: "Paul Ricard (Layout 1A)",
      vehicleClass: "Hypercar & LMGT3 Classes",
      setup: "Open",
      durationMin: 40,
      raceDurationMin: 40,
      eventDurationMin: 51,
      startOffsetMinute: 15,
      splits: 44,
      assists: "No assists allowed",
      tyreWarmers: false,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 30 },
    },
    {
      id: "advanced-elms-super-60",
      name: "ELMS Super 60",
      tier: "advanced",
      licenseLabel: "Gold SR",
      track: "Spa (ELMS)",
      vehicleClass: "LMP2 (ELMS, full fuel tank), LMP3 (70L fuel tank) & LMGT3 Classes (75% VE)",
      setup: "Open",
      durationMin: 60,
      raceDurationMin: 60,
      eventDurationMin: 71,
      startOffsetMinute: 30,
      splits: 44,
      assists: "No assists allowed",
      tyreWarmers: false,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 30 },
    },
    {
      id: "advanced-wec-xperience",
      name: "WEC-Xperience",
      tier: "advanced",
      licenseLabel: "Gold SR",
      track: "Silverstone (ELMS)",
      vehicleClass: "Hypercar & LMGT3 Classes, 75% VE Limit",
      setup: "Open",
      durationMin: 60,
      raceDurationMin: 60,
      eventDurationMin: 71,
      startOffsetMinute: 45,
      splits: 44,
      assists: "No assists allowed",
      tyreWarmers: false,
      tyres: 8,
      recurrence: { kind: "interval", intervalMinutes: 30 },
    },
    // ── Weekly (Solo): WEC Weekly ──
    {
      id: "weekly-wec-weekly",
      name: "WEC Weekly",
      tier: "weekly",
      licenseLabel: "SR S2",
      track: "Portimao (ELMS)",
      vehicleClass: "Hypercar & LMGT3 Classes",
      setup: "Open",
      durationMin: 100,
      raceDurationMin: 100,
      eventDurationMin: 111,
      splits: 44,
      assists: "No assists allowed",
      tyreWarmers: false,
      tyres: 10,
      recurrence: {
        kind: "weekly-slots",
        days: ["Wed", "Thu", "Fri", "Sat", "Sun", "Mon"],
        timesUTC: ["02:00", "06:00", "09:00", "12:00", "15:00", "18:00", "20:00", "23:00"],
      },
    },
    // ── Special Event (Team): ELMS 4h ──
    {
      id: "series-special-imola",
      name: "ELMS 4 Hours of Imola",
      tier: "special",
      licenseLabel: "SR B2",
      track: "Imola (ELMS)",
      vehicleClass: "LMP2 (ELMS) LMP3 & LMGT3 Classes",
      setup: "Open",
      durationMin: 240,
      raceDurationMin: 240,
      eventDurationMin: 240,
      splits: 44,
      assists: "No assists allowed",
      tyreWarmers: false,
      tyres: 14,
      recurrence: {
        kind: "weekly-slots",
        days: ["Fri", "Sat", "Sun"],
        timesUTC: ["03:00", "08:00", "13:00", "18:00", "23:00"],
      },
    },
  ],
  seriesPreviews: [
    { seriesId: "beginner-lmgt3-fixed", scheduleLabel: "Cada 15 min", nextStarts: ["2026-07-07T18:15:00Z", "2026-07-07T18:30:00Z"] },
    { seriesId: "beginner-mclaren-challenge", scheduleLabel: "Cada 15 min", nextStarts: ["2026-07-07T18:30:00Z", "2026-07-07T18:45:00Z"] },
    { seriesId: "beginner-lmp3-fixed", scheduleLabel: "Cada 15 min", nextStarts: ["2026-07-07T18:45:00Z", "2026-07-07T19:00:00Z"] },
    { seriesId: "intermediate-lmgt3-sprint", scheduleLabel: "Cada 20 min", nextStarts: ["2026-07-07T19:15:00Z", "2026-07-07T19:35:00Z"] },
    { seriesId: "intermediate-prototype-fixed", scheduleLabel: "Cada 20 min", nextStarts: ["2026-07-07T19:30:00Z", "2026-07-07T19:50:00Z"] },
    { seriesId: "intermediate-elms-sprint", scheduleLabel: "Cada 20 min", nextStarts: ["2026-07-07T19:45:00Z", "2026-07-07T20:05:00Z"] },
    { seriesId: "advanced-one-stint-sprint", scheduleLabel: "Cada 30 min", nextStarts: ["2026-07-07T20:15:00Z", "2026-07-07T20:45:00Z"] },
    { seriesId: "advanced-elms-super-60", scheduleLabel: "Cada 30 min", nextStarts: ["2026-07-07T20:30:00Z", "2026-07-07T21:00:00Z"] },
    { seriesId: "advanced-wec-xperience", scheduleLabel: "Cada 30 min", nextStarts: ["2026-07-07T20:45:00Z", "2026-07-07T21:15:00Z"] },
    { seriesId: "weekly-wec-weekly", scheduleLabel: "Mié-Sáb, Lun @ 02/06/09/12/15/18/20/23 UTC", nextStarts: ["2026-07-08T02:00:00Z"] },
    { seriesId: "series-special-imola", scheduleLabel: "Vie/Dom @ 03/08/13/18/23 UTC", nextStarts: ["2026-07-10T03:00:00Z", "2026-07-10T08:00:00Z"] },
  ],
};
