import {
  FUNCTIONAL_STUDY_DEFAULT_MODULES,
  FUNCTIONAL_STUDY_MODULES,
  FUNCTIONAL_STUDY_MODULE_IDS,
  FUNCTIONAL_STUDY_SLOTS,
  FUNCTIONAL_STUDY_SLOT_IDS,
  FUNCTIONAL_STUDY_STYLES,
  FUNCTIONAL_STUDY_STYLE_IDS,
  type FunctionalStudyStyleId,
} from "./functional-study-options";

/** Canonical Efficiency names; values and URL IDs remain compatible. */
export const EFFICIENCY_STUDY_MODULES = FUNCTIONAL_STUDY_MODULES;
export const EFFICIENCY_STUDY_MODULE_IDS = FUNCTIONAL_STUDY_MODULE_IDS;
export const EFFICIENCY_STUDY_DEFAULT_MODULES = FUNCTIONAL_STUDY_DEFAULT_MODULES;
export const EFFICIENCY_STUDY_STYLES = FUNCTIONAL_STUDY_STYLES;
export const EFFICIENCY_STUDY_STYLE_IDS = FUNCTIONAL_STUDY_STYLE_IDS;
export const EFFICIENCY_STUDY_SLOTS = FUNCTIONAL_STUDY_SLOTS;
export const EFFICIENCY_STUDY_SLOT_IDS = FUNCTIONAL_STUDY_SLOT_IDS;

export type EfficiencyStudyStyleId = FunctionalStudyStyleId;
