import type { Locale } from "../../../i18n/i18n";

const en = {
  position: "POS", driverNumber: "NO", driverName: "DRIVER", vehicleClass: "CLASS",
  gap: "TO LEADER", paceGap: "TO BEST", interval: "INTERVAL", currentLap: "LAP",
  lastLap: "LAST LAP", bestLap: "BEST LAP", personalBest: "PERSONAL BEST", pit: "PIT", tireCompound: "TYRE",
  you: "YOU", remaining: "REMAINING", race: "RACE", practice: "PRACTICE", qualifying: "QUALIFYING",
  stale: "DATA OUT OF DATE", disconnected: "DISCONNECTED", missing: "NO DATA", error: "DATA ERROR",
  trackTemperature: "TRACK", airTemperature: "AIR", estimatedLaps: "EST. LAPS LEFT", totalLaps: "TOTAL LAPS",
  trackTemp: "TRACK", ambientTemp: "AIR", wind: "WIND", track: "TRACK",
  rain: "RAIN", wetness: "WET", dry: "DRY", pressure: "PRESS",
  relative: "RELATIVE", delta: "DELTA", pedals: "PEDALS", playerGap: "TO YOU",
  clutch: "CLUTCH", brake: "BRAKE", throttle: "THROTTLE",
  fuel: "FUEL", virtualEnergy: "VIRTUAL ENERGY", virtualEnergyUnavailable: "VIRTUAL ENERGY SIGNAL UNAVAILABLE", avg: "AVG", laps: "LAPS", required: "REQ", history: "HISTORY", estFinish: "EST. FINISH",
  aero: "AERO", body: "BODY", suspension: "SUSP", tyre: "TYRE", damage: "DAMAGE",
  speed: "SPEED", rpm: "RPM", gear: "GEAR",
};

export const functionalLabels: Record<Locale, typeof en> = {
  en,
  es: { ...en, driverName: "PILOTO", vehicleClass: "CLASE", gap: "AL LÍDER", paceGap: "AL MEJOR",
    interval: "INTERVALO", currentLap: "VUELTA", lastLap: "ÚLT. VUELTA", bestLap: "MEJOR V.", personalBest: "MEJOR PERSONAL",
    tireCompound: "NEUM.", you: "TÚ", remaining: "RESTANTE", race: "CARRERA", practice: "PRÁCTICA",
    qualifying: "CLASIFICACIÓN", stale: "DATOS ANTIGUOS", disconnected: "DESCONECTADO", missing: "SIN DATOS", error: "ERROR DE DATOS",
    trackTemperature: "PISTA", airTemperature: "AIRE", estimatedLaps: "V. REST. EST.", totalLaps: "V. TOTALES",
    trackTemp: "PISTA", ambientTemp: "AIRE", wind: "VIENTO", track: "PISTA",
    rain: "LLUVIA", wetness: "HÚMEDO", dry: "SECO", pressure: "PRES",
    relative: "RELATIVO", pedals: "PEDALES", playerGap: "A TI", estFinish: "EST. META",
    clutch: "EMBRAGUE", brake: "FRENO", throttle: "ACELERADOR", virtualEnergy: "ENERGÍA VIRTUAL", virtualEnergyUnavailable: "ENERGÍA VIRTUAL NO DISPONIBLE EN LA SEÑAL EN VIVO" },
  pt: { ...en, driverName: "PILOTO", vehicleClass: "CLASSE", gap: "AO LÍDER", paceGap: "AO MELHOR",
    interval: "INTERVALO", currentLap: "VOLTA", lastLap: "ÚLT. VOLTA", bestLap: "MELHOR V.", personalBest: "MELHOR PESSOAL",
    tireCompound: "PNEU", you: "VOCÊ", remaining: "RESTANTE", race: "CORRIDA", practice: "TREINO",
    qualifying: "CLASSIFICAÇÃO", stale: "DADOS ANTIGOS", disconnected: "DESCONECTADO", missing: "SEM DADOS", error: "ERRO DE DADOS",
    trackTemperature: "PISTA", airTemperature: "AR", estimatedLaps: "V. REST. EST.", totalLaps: "V. TOTAIS",
    trackTemp: "PISTA", ambientTemp: "AR", wind: "VENTO", track: "PISTA",
    relative: "RELATIVO", pedals: "PEDAIS", playerGap: "A VOCÊ", estFinish: "EST. FIM",
    clutch: "EMBREAGEM", brake: "FREIO", throttle: "ACELERADOR", virtualEnergy: "ENERGIA VIRTUAL", virtualEnergyUnavailable: "SINAL DE ENERGIA VIRTUAL INDISPONÍVEL" },
  it: { ...en, driverName: "PILOTA", vehicleClass: "CLASSE", gap: "DAL LEADER", paceGap: "DAL MIGLIORE",
    interval: "INTERVALLO", currentLap: "GIRO", lastLap: "ULT. GIRO", bestLap: "MIGLIORE", personalBest: "MIGLIOR PERSONALE",
    tireCompound: "GOMMA", you: "TU", remaining: "RIMANENTE", race: "GARA", practice: "PROVE",
    qualifying: "QUALIFICHE", stale: "DATI NON AGGIORNATI", disconnected: "DISCONNESSO", missing: "NESSUN DATO", error: "ERRORE DATI",
    trackTemperature: "PISTA", airTemperature: "ARIA", estimatedLaps: "GIRI REST. ST.", totalLaps: "GIRI TOTALI",
    trackTemp: "PISTA", ambientTemp: "ARIA", wind: "VENTO", track: "PISTA",
    relative: "RELATIVO", pedals: "PEDALI", playerGap: "A TE", estFinish: "STIMA FINALE",
    clutch: "FRIZIONE", brake: "FRENO", throttle: "ACCELERATORE", virtualEnergy: "ENERGIA VIRTUALE", virtualEnergyUnavailable: "SEGNALE ENERGIA VIRTUALE NON DISPONIBILE" },
};
