// Code generated by tools/generate-lmu-offsets.py; DO NOT EDIT.
// Regenerate: python tools/generate-lmu-offsets.py

package lmu

const ObjectOutSize = 324820

const (
	telemetryTelemStride = 1888
	telemetryTelemOffset = 128468
	vehicleScoringOffset = 2192
	vehicleScoringStride = 584
	scoringInfoOffset    = 1632
	scoringInfoSize      = 548
)

const (
	telemetryPlayerVehicleIdx = 128465
	telemetryPlayerHasVehicle = 128466
)

const (
	vehicleTelemetryID               = 0
	vehicleTelemetryLapNumber        = 20
	vehicleTelemetryLocalVel         = 184
	vehicleTelemetryVehicleName      = 32
	vehicleTelemetryTrackName        = 96
	vehicleTelemetryGear             = 352
	vehicleTelemetryEngineRPM        = 356
	vehicleTelemetryFuel             = 524
	vehicleTelemetryFuelCapacity     = 608
	vehicleTelemetryFilteredThrottle = 420
	vehicleTelemetryFilteredBrake    = 428
	vehicleTelemetryFilteredSteering = 436
	vehicleTelemetryDeltaBest        = 696
)

const (
	scoringTrackName   = 1632
	scoringSession     = 1696
	scoringCurrentET   = 1700
	scoringNumVehicles = 1736
	scoringGamePhase   = 1740
	scoringPlayerName  = 1748
	scoringAmbientTemp = 1860
	scoringTrackTemp   = 1868
)

const (
	vehicleScoringID               = 0
	vehicleScoringDriverName       = 4
	vehicleScoringTotalLaps        = 100
	vehicleScoringIsPlayer         = 196
	vehicleScoringInPits           = 198
	vehicleScoringPlace            = 199
	vehicleScoringVehicleClass     = 200
	vehicleScoringTimeBehindLeader = 244
)

// Size assertions (from pyLMUSharedMemory ctypes layout):
// LMUObjectOut: 324820 bytes
// LMUVehicleTelemetry: 1888 bytes per slot
// LMUVehicleScoring: 584 bytes per slot
// LMUWheel: 260 bytes per wheel
// LMUScoringInfo: 548 bytes
