import type { WidgetRendererProps } from "../../../core/design-system-definition";
import type { DeltaTraceViewModel } from "../../../widget-types/delta-trace/delta-trace-view-model";

const delta = (value: number | undefined) => value === undefined ? "—" : `${value >= 0 ? "+" : ""}${value.toFixed(2)}`;

export function DeltaTraceCrystal({ model }: WidgetRendererProps<DeltaTraceViewModel>) {
  const points = model.points.map((point, index) => `${index === 0 ? "M" : "L"} ${(index / Math.max(1, model.points.length - 1)) * 600} ${40 - point.deltaSeconds * 60}`).join(" ");
  const livePath = points || "M 0 40 L 600 40";
  const markerY = model.points.length > 0 ? 40 - model.points.at(-1)!.deltaSeconds * 60 : 40;
  const panel = (label: string) => <aside><small>{label}</small><i aria-hidden="true" /><span>—</span><time>—</time></aside>;
  return <section data-widget-system="vantare-crystal" data-widget-renderer="delta-trace" data-status={model.status} className="vc-delta-trace"><div className="vc-dt-top">{panel("ALL")}<div className="vc-dt-graph"><strong>{delta(model.currentDelta)}</strong><svg viewBox="0 0 600 80" preserveAspectRatio="none" role="img" aria-label="Delta trace"><defs><linearGradient id="vc-dt-live-gradient" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="rgba(34,197,94,0.5)" /><stop offset="100%" stopColor="rgba(34,197,94,0)" /></linearGradient></defs><line x1="0" y1="40" x2="600" y2="40"/>{[[60, 25], [120, 40], [200, 20], [250, 18], [290, 18], [350, 30], [450, 25], [520, 35]].map(([x, width]) => <rect height="80" key={x} width={width} x={x} y="0" />)}<path className="vc-dt-reference" d="M 0 20 Q 80 65 150 45 T 300 20 T 450 65 T 600 25"/><path className="vc-dt-live-fill" d={`${livePath} L 600 40 L 0 40 Z`}/><path className="vc-dt-live" d={livePath}/><line className="vc-dt-marker-line" x1="600" x2="600" y1="30" y2={markerY}/><circle className="vc-dt-marker-dot" cx="600" cy={markerY} r="3"/></svg><div className="vc-dt-turn-numbers">{[1, 3, 4, 5, 6, 7, 9, 10, 11, 12, 13, 14, 16].map((turn) => <span key={turn}>{turn}</span>)}</div></div>{panel("SB")}</div><div className="vc-dt-bottom"><div className="vc-dt-sectors">{Array.from({ length: 14 }, (_, index) => <i key={index}>{model.sectorDeltas[index] === undefined ? "" : delta(model.sectorDeltas[index])}</i>)}</div><div className="vc-dt-turn"><div><small>TURN</small><b>{model.turnInsight ?? "—"}</b></div><em>{model.trend.toUpperCase()}</em></div><div className="vc-dt-map">{model.trackPath ? <svg viewBox="0 0 100 50"><path d={model.trackPath}/></svg> : <span>MAP —</span>}</div></div></section>;
}
