import type { WidgetType } from "../core/profile-document";
import { validateWidgetDesign, type WidgetDesignV1 } from "../core/widget-design";
import { PEDALS_DEFAULT_APPEARANCE } from "../widget-types/pedals/pedals-renderer-helpers";
import { RELATIVE_DEFAULT_APPEARANCE } from "../widget-types/relative/relative-renderer-helpers";

export const OFFICIAL_DESIGNS_SECTION_LABEL = "Diseños de Vantare";

const OFFICIAL_DESIGN_DEFINITIONS: WidgetDesignV1[] = [
  {
    id: "delta-original-base",
    name: "Original Base",
    widgetType: "delta",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: { showHeader: true },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "delta-crystal-bar",
    name: "Crystal Bar",
    widgetType: "delta",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 2,
    visual: { templateId: "delta-bar", showHeader: true },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "delta-time-attack",
    name: "Time Attack",
    widgetType: "delta",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: { showHeader: false, accent: "amber" },
    includesContent: false,
    origin: "vantare",
  },
  {
    id: "delta-crystal-simple",
    name: "Crystal Simple",
    widgetType: "delta",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 2,
    visual: { templateId: "delta-simple", showHeader: true },
    includesContent: false,
    origin: "vantare",
  },
  {
    id: "standings-original-base",
    name: "Original Base",
    widgetType: "standings",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: { showSessionHeader: true, compactRows: false },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "standings-crystal-vertical",
    name: "Crystal Vertical",
    widgetType: "standings",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 2,
    visual: { showSessionHeader: true, compactRows: false, templateId: "standings-vertical" },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "relative-original-base",
    name: "Original Base",
    widgetType: "relative",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: { ...RELATIVE_DEFAULT_APPEARANCE },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "relative-crystal-vertical",
    name: "Crystal Vertical",
    widgetType: "relative",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 2,
    visual: { ...RELATIVE_DEFAULT_APPEARANCE, templateId: "relative-vertical" },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "pedals-original-base",
    name: "Original Base",
    widgetType: "pedals",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: { ...PEDALS_DEFAULT_APPEARANCE },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "pedals-crystal",
    name: "Crystal V3",
    widgetType: "pedals",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 2,
    visual: { ...PEDALS_DEFAULT_APPEARANCE, templateId: "pedals" },
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "pedals-telemetry-original",
    name: "Original Telemetry",
    widgetType: "pedals-telemetry",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: {},
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "pedals-telemetry-crystal",
    name: "Crystal V1 Capsule",
    widgetType: "pedals-telemetry",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 1,
    visual: {},
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "pedals-telemetry-compact-original",
    name: "Original Compact Telemetry",
    widgetType: "pedals-telemetry-compact",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: {},
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "pedals-telemetry-compact-crystal",
    name: "Crystal V2 Low Profile",
    widgetType: "pedals-telemetry-compact",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 1,
    visual: {},
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "racing-flags-original",
    name: "Original Racing Flags",
    widgetType: "racing-flags",
    systemId: "vantare-original",
    systemVersion: 1,
    configVersion: 1,
    visual: {},
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  {
    id: "racing-flags-crystal",
    name: "Crystal Racing Flags",
    widgetType: "racing-flags",
    systemId: "vantare-crystal",
    systemVersion: 1,
    configVersion: 1,
    visual: {},
    includesContent: false,
    origin: "vantare",
    isDefault: true,
  },
  { id: "broadcast-tower-original", name: "Original Broadcast Tower", widgetType: "broadcast-tower", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "broadcast-tower-crystal", name: "Crystal Broadcast Tower", widgetType: "broadcast-tower", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "head-to-head-original", name: "Original Head to Head", widgetType: "head-to-head", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "head-to-head-crystal", name: "Crystal Head to Head", widgetType: "head-to-head", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "input-telemetry-original", name: "Original Input Telemetry", widgetType: "input-telemetry", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "input-crystal-blade", name: "Crystal Input Blade", widgetType: "input-telemetry", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: { templateId: "input-blade" }, includesContent: false, origin: "vantare", isDefault: true },
  { id: "input-crystal-capsule", name: "Crystal Input Capsule", widgetType: "input-telemetry", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: { templateId: "input-capsule" }, includesContent: false, origin: "vantare" },
  { id: "input-crystal-dense", name: "Crystal Input Dense", widgetType: "input-telemetry", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: { templateId: "input-dense" }, includesContent: false, origin: "vantare" },
  { id: "multiclass-relative-original", name: "Original Multiclass Relative", widgetType: "multiclass-relative", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "multiclass-relative-crystal", name: "Crystal Multiclass Relative", widgetType: "multiclass-relative", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "delta-advanced-original", name: "Original Delta Advanced", widgetType: "delta-advanced", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "delta-advanced-crystal", name: "Crystal Delta Advanced", widgetType: "delta-advanced", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "fuel-strategy-original", name: "Original Fuel Strategy", widgetType: "fuel-strategy", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "fuel-strategy-crystal-unified", name: "Crystal Fuel Strategy", widgetType: "fuel-strategy", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "delta-trace-original", name: "Original Delta Trace", widgetType: "delta-trace", systemId: "vantare-original", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
  { id: "delta-trace-crystal", name: "Crystal Delta Trace", widgetType: "delta-trace", systemId: "vantare-crystal", systemVersion: 1, configVersion: 1, visual: {}, includesContent: false, origin: "vantare", isDefault: true },
];

const OFFICIAL_DESIGNS: WidgetDesignV1[] = OFFICIAL_DESIGN_DEFINITIONS.map((design) =>
  validateWidgetDesign(design),
);

const OFFICIAL_BY_ID = new Map(OFFICIAL_DESIGNS.map((design) => [design.id, design]));

export function listOfficialDesigns(widgetType?: WidgetType): WidgetDesignV1[] {
  if (!widgetType) {
    return [...OFFICIAL_DESIGNS];
  }
  return OFFICIAL_DESIGNS.filter((design) => design.widgetType === widgetType);
}

export function getOfficialDesign(id: string): WidgetDesignV1 | undefined {
  return OFFICIAL_BY_ID.get(id);
}
