// Generated by scripts/generate-official-design-declarations.mjs. Do not edit.
import { officialWidgetDesignDeclarations as declarations0 } from "./vantare-crystal/delta/official-designs";

export const OFFICIAL_WIDGET_DESIGN_DECLARATIONS = [
  ...declarations0,
] as const;
