// Code generated by build/windows/telemetry-reader/build-runtime.ps1; DO NOT EDIT.

package duckdbadapter

const productionManifestSHA256 = "ee387ce9b36a957e3ec30b7f4b1ab5878a09516a79c6adae32e87c5e3761b0d0"
