// Code generated by build/windows/telemetry-reader/build-runtime.ps1; DO NOT EDIT.

package duckdbadapter

const productionManifestSHA256 = "700201f90266ae6b829372d9989408c6b0efd86725a50980d46fc05adfc24869"
