// Code generated by build/windows/telemetry-reader/build-runtime.ps1; DO NOT EDIT.

package duckdbadapter

const productionManifestSHA256 = "132fd8b6ace1cf33680011275b821fe20b210111bcb8d57dabd3d1136ebe79c7"
