import fs from 'node:fs';import path from 'node:path';import {pathToFileURL,fileURLToPath} from 'node:url';
import {experimentPlugin} from './experiment-transforms.mjs';
const [rootArg,outArg,label='base',experiment='none']=process.argv.slice(2);const root=path.resolve(rootArg),output=path.resolve(outArg);fs.mkdirSync(output,{recursive:true});
const {createServer}=await import(pathToFileURL(path.join(root,'node_modules/vite/dist/node/index.js')));
const {chromium}=await import(pathToFileURL(path.join(root,'node_modules/playwright/index.mjs')));
const harness=fs.readFileSync(new URL('./react-harness.tsx',import.meta.url),'utf8').replace('REPLACE_APP_ROOT',path.dirname(root));
const server=await createServer({root,envDir:path.join(output,'no-env-files'),server:{host:'127.0.0.1',port:5198,strictPort:true},plugins:[experimentPlugin(experiment,output),{name:'astra-harness',resolveId(id){if(id==='/astra-harness.tsx')return path.join(root,'astra-harness.tsx');},load(id){if(id===path.join(root,'astra-harness.tsx'))return harness;},configureServer(s){s.middlewares.use(async(req,res,next)=>{if(req.url!=='/astra-audit')return next();res.setHeader('Content-Type','text/html');res.end(await s.transformIndexHtml('/astra-audit','<html><body><div id="root"></div><script type="module" src="/astra-harness.tsx"></script></body></html>'));});}}]});
let browser;
try{await server.listen();browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1280,height:800}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:5198/astra-audit');await page.waitForFunction(()=>window.astra);const cdp=await page.context().newCDPSession(page);await cdp.send('Performance.enable');await cdp.send('HeapProfiler.collectGarbage');const before=await cdp.send('Memory.getDOMCounters');
const cycles10=await page.evaluate(()=>window.astra.cycles(10));await cdp.send('HeapProfiler.collectGarbage');const after10=await cdp.send('Memory.getDOMCounters');const cycles50=await page.evaluate(()=>window.astra.cycles(50));await cdp.send('HeapProfiler.collectGarbage');const after50=await cdp.send('Memory.getDOMCounters');const metricsBefore=await cdp.send('Performance.getMetrics');await cdp.send('Profiler.enable');await cdp.send('Profiler.start');
const runs=[];for(let i=0;i<3;i++)runs.push(await page.evaluate(()=>window.astra.run(180)));
const cpu=await cdp.send('Profiler.stop');fs.writeFileSync(path.join(output,`${label}-react.cpuprofile`),JSON.stringify(cpu.profile));const metricsAfter=await cdp.send('Performance.getMetrics');await page.evaluate(()=>window.astra.stop());await cdp.send('HeapProfiler.collectGarbage');const after=await cdp.send('Memory.getDOMCounters');
const record={label,classification:'MEASURED-MAC-AUXILIARY',browser:browser.version(),fixture:'golden V2 + synthetic 44 moving ground positions; level 3, track-map/pedals/standings; React development profiling build',before,cycles10,after10,cycles50,after50,after,runs,metricsBefore,metricsAfter,errors};fs.writeFileSync(path.join(output,`${label}-react.json`),JSON.stringify(record,null,2));console.log(JSON.stringify({...record,runs:runs.map(r=>({...r,commits:r.commits.length,frameIntervals:undefined}))},null,2));if(errors.length||runs.some(r=>r.diagnostics||!r.renderers)||cycles50.subscriptions)process.exitCode=1;
}finally{await browser?.close();await server.close();}
