//! Artwork estático productivo; no registro ni renderer paralelo.
pub(super) fn svg(wheel: &str) -> &'static str {
    match wheel {
        "alpine-a424" => include_str!("wheels/alpine-a424.svg"),
        "aston-martin-valkyrie" => include_str!("wheels/aston-martin-valkyrie.svg"),
        "bmw-m-hybrid-v8-pre-le-mans" => include_str!("wheels/bmw-m-hybrid-v8-pre-le-mans.svg"),
        "bmw-m-hybrid-v8" => include_str!("wheels/bmw-m-hybrid-v8.svg"),
        "cadillac-v-series-r" => include_str!("wheels/cadillac-v-series-r.svg"),
        "ferrari-499p" => include_str!("wheels/ferrari-499p.svg"),
        "genesis-gmr-001" => include_str!("wheels/genesis-gmr-001.svg"),
        "glickenhaus-scg007" => include_str!("wheels/glickenhaus-scg007.svg"),
        "isotta-fraschini-tipo6" => include_str!("wheels/isotta-fraschini-tipo6.svg"),
        "lamborghini-sc63" => include_str!("wheels/lamborghini-sc63.svg"),
        "peugeot-9x8" => include_str!("wheels/peugeot-9x8.svg"),
        "peugeot-9x8-2024" => include_str!("wheels/peugeot-9x8-2024.svg"),
        "porsche-963" => include_str!("wheels/porsche-963.svg"),
        "toyota-gr010" | "toyota-tr010" => include_str!("wheels/toyota-gr010.svg"),
        "vanwall-vandervell-680" => include_str!("wheels/vanwall-vandervell-680.svg"),
        "aston-martin-vantage-gt3" => include_str!("wheels/aston-martin-vantage-gt3.svg"),
        "bmw-m4-gt3" => include_str!("wheels/bmw-m4-gt3.svg"),
        "corvette-z06-gt3" => include_str!("wheels/corvette-z06-gt3.svg"),
        "ferrari-296-gt3" => include_str!("wheels/ferrari-296-gt3.svg"),
        "ford-mustang-gt3" => include_str!("wheels/ford-mustang-gt3.svg"),
        "lamborghini-huracan-gt3" => include_str!("wheels/lamborghini-huracan-gt3.svg"),
        "lexus-rc-f-gt3" => include_str!("wheels/lexus-rc-f-gt3.svg"),
        "mclaren-720s-gt3" => include_str!("wheels/mclaren-720s-gt3.svg"),
        "mercedes-amg-gt3" => include_str!("wheels/mercedes-amg-gt3.svg"),
        "porsche-911-gt3-r" => include_str!("wheels/porsche-911-gt3-r.svg"),
        "oreca-07" => include_str!("wheels/oreca-07.svg"),
        "adess-ad25" => include_str!("wheels/adess-ad25.svg"),
        "duqueine-d09" => include_str!("wheels/duqueine-d09.svg"),
        "ginetta-g61-lt-p3-evo" => include_str!("wheels/ginetta-g61-lt-p3-evo.svg"),
        "ligier-js-p325" => include_str!("wheels/ligier-js-p325.svg"),
        _ => include_str!("wheel.svg"),
    }
}
