param(
  [string]$OutFile = "cmd/vantare/supabase_build.go"
)

$url = $env:VANTARE_SUPABASE_URL
$key = $env:VANTARE_SUPABASE_ANON_KEY
$licensePublicKeys = $env:VANTARE_LICENSE_PUBLIC_KEYS

if (-not $url -and -not $key -and -not $licensePublicKeys) {
  # No Supabase config to embed. Remove any stale generated file.
  if (Test-Path -LiteralPath $OutFile) {
    Remove-Item -LiteralPath $OutFile -Force
  }
  exit 0
}

# Encode as base64 so the values survive PowerShell string interpolation
# without escaping issues. The Go init() decodes them at startup.
# Cada valor se castea a [string]: el guard de arriba solo sale cuando faltan
# los tres, asi que aqui cualquiera puede seguir siendo $null por separado y
# GetBytes($null) lanzaria ArgumentNullException. Es el caso normal en dev:
# start-wails-dev.ps1 define las dos de Supabase pero no la de licencias.
$b64Url = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes([string]$url))
$b64Key = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes([string]$key))
$b64LicensePublicKeys = [Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes([string]$licensePublicKeys))

$content = @"
// Code generated by build tool. DO NOT EDIT.

package main

import "encoding/base64"

func init() {
  if decoded, err := base64.StdEncoding.DecodeString("$b64Url"); err == nil {
    supabaseURL = string(decoded)
  }
  if decoded, err := base64.StdEncoding.DecodeString("$b64Key"); err == nil {
    supabaseAnonKey = string(decoded)
  }
  if decoded, err := base64.StdEncoding.DecodeString("$b64LicensePublicKeys"); err == nil {
    licensePublicKeys = string(decoded)
  }
}
"@

if (Test-Path -LiteralPath $OutFile) {
  $existing = Get-Content -LiteralPath $OutFile -Raw
  if ($existing -eq $content) {
    exit 0
  }
}

Set-Content -NoNewline -LiteralPath $OutFile -Value $content
