package main

import (
	"fmt"
	"math"
	"os"
	"strings"
	"unicode"
)

// writePack emits the TypeScript pack consumed by the overlay.
//
// Coordinates are rounded to the metre and stored as a flat number array. The
// outline is only ever drawn a few hundred pixels wide, so finer precision
// would inflate the bundle for a difference nobody can see.
func writePack(path string, results []trackResult) error {
	var builder strings.Builder
	builder.WriteString(`import type { TrackGeometry, TrackPoint } from "./track-geometry";

/** Identifies the authoring placeholder used by Studio and Workshop previews. */
export const REFERENCE_LOOP_ID = "vantare-reference-loop";

type PackedTrack = Readonly<{
  id: string;
  label: string;
  aliases: readonly string[];
  /** Alternating world X and Z in metres, rounded to the metre. */
  coordinates: readonly number[];
}>;

// Generated by tools/trackgeometry from recorded Le Mans Ultimate telemetry.
// Do not edit by hand: regenerate instead.
const PACKED_TRACKS: readonly PackedTrack[] = [
`)

	for _, result := range results {
		builder.WriteString("  {\n")
		fmt.Fprintf(&builder, "    id: %q,\n", identifier(result.track))
		fmt.Fprintf(&builder, "    label: %q,\n", result.track)
		fmt.Fprintf(&builder, "    aliases: [%q],\n", result.track)
		builder.WriteString("    coordinates: [\n      ")
		for index, point := range result.outline.Points {
			if index > 0 {
				builder.WriteString(", ")
				if index%12 == 0 {
					builder.WriteString("\n      ")
				}
			}
			fmt.Fprintf(&builder, "%d, %d", int(math.Round(point.X)), int(math.Round(point.Z)))
		}
		builder.WriteString(",\n    ],\n  },\n")
	}

	builder.WriteString(`];

function unpack(track: PackedTrack): TrackGeometry {
  const points: TrackPoint[] = [];
  for (let index = 0; index + 1 < track.coordinates.length; index += 2) {
    points.push({ x: track.coordinates[index], z: track.coordinates[index + 1] });
  }
  return {
    id: track.id,
    label: track.label,
    synthetic: false,
    aliases: track.aliases,
    points,
  };
}

/**
 * Static circuit geometry shipped with the build.
 *
 * The real circuits are derived from recorded telemetry: LMU stores vehicle
 * position as pseudo-geographic degrees anchored at 60N, 0E, which is a linear
 * map of the same world plane the shared memory reports. The reference loop is
 * a synthetic placeholder kept for authoring previews only.
 */
export const TRACK_GEOMETRY_PACK: readonly TrackGeometry[] = [
  ...PACKED_TRACKS.map(unpack),
  referenceLoop(),
];

/**
 * A deterministic closed curve, in metres, used so the widget can be laid out
 * and styled without a live session. It is marked synthetic, and its name
 * matches no real circuit, so a live session can never resolve it by accident.
 */
function referenceLoop(): TrackGeometry {
  const sampleCount = 96;
  const points: TrackPoint[] = [];
  for (let index = 0; index < sampleCount; index += 1) {
    const angle = (index / sampleCount) * Math.PI * 2;
    const radius = 620 + 180 * Math.sin(angle * 2) + 90 * Math.cos(angle * 3);
    points.push({ x: radius * Math.cos(angle), z: radius * Math.sin(angle) * 0.72 });
  }
  return {
    id: REFERENCE_LOOP_ID,
    label: "Vantare Reference Loop",
    synthetic: true,
    aliases: [],
    points,
  };
}
`)

	return os.WriteFile(path, []byte(builder.String()), 0o644)
}

// identifier turns a circuit name into a stable kebab-case id.
func identifier(name string) string {
	var builder strings.Builder
	previousDash := true
	for _, symbol := range strings.ToLower(fold(name)) {
		switch {
		case symbol >= 'a' && symbol <= 'z', symbol >= '0' && symbol <= '9':
			builder.WriteRune(symbol)
			previousDash = false
		case !previousDash:
			builder.WriteRune('-')
			previousDash = true
		}
	}
	return strings.Trim(builder.String(), "-")
}

// fold strips the diacritics that appear in circuit names such as Autodromo
// Jose Carlos Pace, so identifiers stay ASCII.
func fold(value string) string {
	var builder strings.Builder
	for _, symbol := range value {
		switch {
		case symbol >= 'a' && symbol <= 'z', symbol >= 'A' && symbol <= 'Z',
			symbol >= '0' && symbol <= '9', unicode.IsSpace(symbol):
			builder.WriteRune(symbol)
		default:
			builder.WriteRune(foldRune(symbol))
		}
	}
	return builder.String()
}

func foldRune(symbol rune) rune {
	const accented = "áàâäãåéèêëíìîïóòôöõúùûüñçÁÀÂÄÃÅÉÈÊËÍÌÎÏÓÒÔÖÕÚÙÛÜÑÇ"
	const plain = "aaaaaaeeeeiiiiooooouuuuncAAAAAAEEEEIIIIOOOOOUUUUNC"
	if index := strings.IndexRune(accented, symbol); index >= 0 {
		return []rune(plain)[len([]rune(accented[:index]))]
	}
	return ' '
}
