package main

import (
	"os"
	"path/filepath"
	"reflect"
	"regexp"
	"sort"
	"strings"
	"testing"
)

type tsField struct {
	typeName string
	optional bool
}

func TestGeneratedContractMatchesHandwritten(t *testing.T) {
	t.Parallel()

	generatedBytes, err := generate()
	if err != nil {
		t.Fatalf("generate contract: %v", err)
	}
	generated := string(generatedBytes)
	transport := handwrittenTransportContract
	overlayMirror := readRepositoryFile(t, "frontend", "src", "overlay", "projection", "overlay-projection-v1.ts")

	compareFields(t, "ProjectionEnvelope",
		interfaceFields(t, generated, "ProjectionEnvelope"),
		typeLiteralFields(t, transport, "ProjectionEnvelope"), nil)
	compareFields(t, "StatusEnvelope",
		withoutField(interfaceFields(t, generated, "StatusEnvelope"), "payload"),
		withoutField(typeLiteralFields(t, transport, "StatusEnvelope"), "payload"), nil)
	compareFields(t, "StatusPayload",
		interfaceFields(t, generated, "StatusPayload"),
		nestedTypeLiteralFields(t, transport, "StatusEnvelope", "payload"), nil)
	compareFields(t, "FactEnvelope",
		interfaceFields(t, generated, "FactEnvelope"),
		typeLiteralFields(t, transport, "FactEnvelope"), nil)

	fieldAliases := map[string]string{
		"TelemetryField": "OverlayProjectionField",
	}
	vehicle := interfaceFields(t, generated, "OverlayVehicleV1")
	compareFields(t, "OverlayVehicleV1", vehicle,
		typeLiteralFields(t, overlayMirror, "OverlayVehicleV1"), fieldAliases)
	if got := len(vehicle); got != 30 {
		t.Fatalf("OverlayVehicleV1 generated %d fields; Go wire currently has 30", got)
	}
	compareFields(t, "OverlayGroundPositionV1",
		interfaceFields(t, generated, "OverlayGroundPositionV1"),
		typeLiteralFields(t, overlayMirror, "OverlayGroundPositionV1"), nil)

	compareValues(t, "ProductID", enumValues(t, generated, "ProductID"),
		constArrayValues(t, transport, "TELEMETRY_PRODUCTS"))
	compareValues(t, "StatusState", enumValues(t, generated, "StatusState"),
		constArrayValues(t, transport, "TELEMETRY_STATUS_STATES"))
	compareValues(t, "SnapshotKind", enumValues(t, generated, "SnapshotKind"), []string{"full"})
	compareValues(t, "EventKind", enumValues(t, generated, "EventKind"), []string{"projection", "status", "fact"})
}

func TestGeneratedOverlayV2ContractUsesCompactGenericQuality(t *testing.T) {
	t.Parallel()

	generatedBytes, err := generate()
	if err != nil {
		t.Fatalf("generate contract: %v", err)
	}
	generated := string(generatedBytes)
	compareFields(t, "OverlayUpdateV2", interfaceFields(t, generated, "OverlayUpdateV2"), map[string]tsField{
		"revision": {typeName: "number"},
		"source":   {typeName: "OverlaySourceStatusV2"},
		"frame":    {typeName: "OverlayFrameV2 | null"},
	}, nil)
	compareFields(t, "OverlayQValue", interfaceFields(t, generated, "OverlayQValue<T>"), map[string]tsField{
		"q": {typeName: "OverlayQualityV2"},
		"v": {typeName: "T | undefined", optional: true},
	}, nil)
	compareValues(t, "OverlayQualityV2", enumValues(t, generated, "OverlayQualityV2"),
		[]string{"fresh", "invalid", "missing", "stale"})
	if strings.Contains(generated, "interface Overlayv2QValue") {
		t.Fatal("generic QValue was emitted as a duplicated concrete interface")
	}
}

// handwrittenTransportContract is the pre-F5 transport mirror characterized
// by F5.2. It is test evidence only; production TypeScript reexports the Go-
// generated declarations after F5.3.
const handwrittenTransportContract = `
export const TELEMETRY_PRODUCTS = ["overlay", "engineer", "strategy", "analysis"] as const;
export const TELEMETRY_STATUS_STATES = ["stopped", "detecting", "connecting", "live", "degraded", "stale", "error", "stopping"] as const;
export type ProjectionEnvelope = {
  product: ProductID;
  projectionVersion: number;
  epoch: number;
  sequence: number;
  kind: SnapshotKind;
  capturedAt: string;
  statusRevision: number;
  payload: JSONObject;
};
export type StatusEnvelope = {
  product: ProductID;
  statusRevision: number;
  capturedAt: string;
  payload: {
    state: StatusState;
    reconnectAttempt: number;
  };
};
export type FactEnvelope = {
  product: ProductID;
  projectionVersion: number;
  epoch: number;
  sequence: number;
  factSequence: number;
  capturedAt: string;
  statusRevision: number;
  payload: JSONObject;
};
`

func TestGenerateIsDeterministic(t *testing.T) {
	t.Parallel()

	first, err := generate()
	if err != nil {
		t.Fatalf("first generation: %v", err)
	}
	second, err := generate()
	if err != nil {
		t.Fatalf("second generation: %v", err)
	}
	if !reflect.DeepEqual(first, second) {
		t.Fatal("two generations in the same source tree produced different bytes")
	}
	if !strings.HasPrefix(string(first), "// DO NOT EDIT — generated by tools/telemetry-contract-gen") {
		t.Fatal("generated contract has no DO NOT EDIT header")
	}
}

func TestCheckGeneratedRejectsStaleOutput(t *testing.T) {
	t.Parallel()

	generated, err := generate()
	if err != nil {
		t.Fatalf("generate contract: %v", err)
	}
	output := filepath.Join(t.TempDir(), "telemetry.ts")
	if err := os.WriteFile(output, generated, 0o644); err != nil {
		t.Fatalf("write current contract: %v", err)
	}
	if err := checkGenerated(output, generated); err != nil {
		t.Fatalf("current generated contract rejected: %v", err)
	}
	if err := os.WriteFile(output, append(generated, []byte("// stale\n")...), 0o644); err != nil {
		t.Fatalf("write stale contract: %v", err)
	}
	if err := checkGenerated(output, generated); err == nil {
		t.Fatal("stale generated contract was accepted")
	}
}

func readRepositoryFile(t *testing.T, pathParts ...string) string {
	t.Helper()
	path := filepath.Join(append([]string{"..", ".."}, pathParts...)...)
	content, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s: %v", path, err)
	}
	return string(content)
}

func interfaceFields(t *testing.T, source, name string) map[string]tsField {
	t.Helper()
	body := declarationBody(t, source, "export interface "+name)
	return fieldsAtDepth(t, body)
}

func typeLiteralFields(t *testing.T, source, name string) map[string]tsField {
	t.Helper()
	body := declarationBody(t, source, "export type "+name)
	return fieldsAtDepth(t, body)
}

func nestedTypeLiteralFields(t *testing.T, source, typeName, fieldName string) map[string]tsField {
	t.Helper()
	body := declarationBody(t, source, "export type "+typeName)
	fieldStart := regexp.MustCompile(`(?m)^\s*` + regexp.QuoteMeta(fieldName) + `\??:\s*\{`).FindStringIndex(body)
	if fieldStart == nil {
		t.Fatalf("%s.%s nested type literal not found", typeName, fieldName)
	}
	open := strings.Index(body[fieldStart[0]:fieldStart[1]], "{") + fieldStart[0]
	close := matchingBrace(t, body, open)
	return fieldsAtDepth(t, body[open+1:close])
}

func declarationBody(t *testing.T, source, marker string) string {
	t.Helper()
	start := strings.Index(source, marker)
	if start < 0 {
		t.Fatalf("declaration %q not found", marker)
	}
	open := strings.Index(source[start:], "{")
	if open < 0 {
		t.Fatalf("declaration %q has no body", marker)
	}
	open += start
	close := matchingBrace(t, source, open)
	return source[open+1 : close]
}

func matchingBrace(t *testing.T, source string, open int) int {
	t.Helper()
	depth := 0
	for index := open; index < len(source); index++ {
		switch source[index] {
		case '{':
			depth++
		case '}':
			depth--
			if depth == 0 {
				return index
			}
		}
	}
	t.Fatal("unbalanced TypeScript braces")
	return -1
}

func fieldsAtDepth(t *testing.T, body string) map[string]tsField {
	t.Helper()
	result := make(map[string]tsField)
	depth := 0
	start := 0
	for index := 0; index < len(body); index++ {
		switch body[index] {
		case '{':
			depth++
		case '}':
			depth--
		case ';':
			if depth == 0 {
				parseField(t, result, body[start:index])
				start = index + 1
			}
		}
	}
	parseField(t, result, body[start:])
	return result
}

var fieldPattern = regexp.MustCompile(`(?s)^\s*(?:readonly\s+)?([A-Za-z0-9_]+)(\?)?\s*:\s*(.+)\s*$`)

func parseField(t *testing.T, fields map[string]tsField, declaration string) {
	t.Helper()
	match := fieldPattern.FindStringSubmatch(declaration)
	if match == nil {
		if strings.TrimSpace(declaration) == "" {
			return
		}
		t.Fatalf("cannot parse TypeScript field %q", strings.TrimSpace(declaration))
	}
	fields[match[1]] = tsField{typeName: normalizeType(match[3], nil), optional: match[2] == "?"}
}

func compareFields(t *testing.T, name string, generated, handwritten map[string]tsField, aliases map[string]string) {
	t.Helper()
	generated = normalizedFields(generated, aliases)
	if !reflect.DeepEqual(generated, handwritten) {
		t.Fatalf("%s differs from the handwritten mirror\ngenerated: %#v\nhandwritten: %#v", name, generated, handwritten)
	}
}

func normalizedFields(fields map[string]tsField, aliases map[string]string) map[string]tsField {
	result := make(map[string]tsField, len(fields))
	for name, field := range fields {
		field.typeName = normalizeType(field.typeName, aliases)
		result[name] = field
	}
	return result
}

func normalizeType(value string, aliases map[string]string) string {
	value = strings.Join(strings.Fields(value), " ")
	for from, to := range aliases {
		value = strings.ReplaceAll(value, from, to)
	}
	return value
}

func withoutField(fields map[string]tsField, name string) map[string]tsField {
	result := make(map[string]tsField, len(fields)-1)
	for fieldName, field := range fields {
		if fieldName != name {
			result[fieldName] = field
		}
	}
	return result
}

func enumValues(t *testing.T, source, name string) []string {
	t.Helper()
	pattern := regexp.MustCompile(`(?m)^export type ` + regexp.QuoteMeta(name) + ` = ([^;]+);$`)
	match := pattern.FindStringSubmatch(source)
	if match == nil {
		t.Fatalf("generated enum %s not found", name)
	}
	return quotedValues(match[1])
}

func constArrayValues(t *testing.T, source, name string) []string {
	t.Helper()
	pattern := regexp.MustCompile(`(?s)export const ` + regexp.QuoteMeta(name) + `\s*=\s*\[(.*?)\]\s*as const`)
	match := pattern.FindStringSubmatch(source)
	if match == nil {
		t.Fatalf("handwritten const array %s not found", name)
	}
	return quotedValues(match[1])
}

func quotedValues(source string) []string {
	matches := regexp.MustCompile(`"([^"]+)"`).FindAllStringSubmatch(source, -1)
	result := make([]string, len(matches))
	for index, match := range matches {
		result[index] = match[1]
	}
	sort.Strings(result)
	return result
}

func compareValues(t *testing.T, name string, generated, handwritten []string) {
	t.Helper()
	sort.Strings(generated)
	sort.Strings(handwritten)
	if !reflect.DeepEqual(generated, handwritten) {
		t.Fatalf("%s differs: generated=%v handwritten=%v", name, generated, handwritten)
	}
}
