// Command telemetry-contract-gen generates the TypeScript telemetry wire contract.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	"github.com/vantare/overlays/v2/internal/app/telemetrytransport"
	"github.com/vantare/overlays/v2/internal/telemetry/projection"
	"github.com/vantare/overlays/v2/internal/telemetry/projection/analysis"
	"github.com/vantare/overlays/v2/internal/telemetry/projection/engineer"
	"github.com/vantare/overlays/v2/internal/telemetry/projection/overlay"
	"github.com/vantare/overlays/v2/internal/telemetry/projection/overlayv2"
	"github.com/vantare/overlays/v2/internal/telemetry/projection/strategy"
)

const defaultOutput = "frontend/src/generated/telemetry.ts"

var rawMessageType = reflect.TypeFor[json.RawMessage]()

type enumRoot struct {
	typeOf reflect.Type
	name   string
	values []string
}

type structRoot struct {
	typeOf reflect.Type
	name   string
}

type generator struct {
	names      map[reflect.Type]string
	structs    map[reflect.Type]structRoot
	enums      map[reflect.Type]enumRoot
	fieldTypes map[string]string
	reserved   map[string]reflect.Type
}

func main() {
	output := flag.String("out", defaultOutput, "generated TypeScript output path")
	check := flag.Bool("check", false, "compare a temporary generation with the committed output")
	flag.Parse()

	generated, err := generate()
	if err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if *check {
		if err := checkGenerated(*output, generated); err != nil {
			fmt.Fprintln(os.Stderr, err)
			os.Exit(1)
		}
		return
	}
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "create output directory: %v\n", err)
		os.Exit(1)
	}
	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "write generated contract: %v\n", err)
		os.Exit(1)
	}
}

func checkGenerated(output string, generated []byte) error {
	temporary, err := os.CreateTemp("", "vantare-telemetry-contract-*.ts")
	if err != nil {
		return fmt.Errorf("create temporary contract: %w", err)
	}
	temporaryPath := temporary.Name()
	defer os.Remove(temporaryPath)
	if _, err := temporary.Write(generated); err != nil {
		temporary.Close()
		return fmt.Errorf("write temporary contract: %w", err)
	}
	if err := temporary.Close(); err != nil {
		return fmt.Errorf("close temporary contract: %w", err)
	}

	committed, err := os.Open(output)
	if err != nil {
		return fmt.Errorf("open committed contract: %w", err)
	}
	defer committed.Close()
	temporary, err = os.Open(temporaryPath)
	if err != nil {
		return fmt.Errorf("open temporary contract: %w", err)
	}
	defer temporary.Close()
	equal, err := sameBytes(committed, temporary)
	if err != nil {
		return fmt.Errorf("compare generated contract: %w", err)
	}
	if !equal {
		return fmt.Errorf("%s is stale; regenerate with `task telemetry:contract`", output)
	}
	return nil
}

func sameBytes(left, right io.Reader) (bool, error) {
	leftBytes, err := io.ReadAll(left)
	if err != nil {
		return false, err
	}
	rightBytes, err := io.ReadAll(right)
	if err != nil {
		return false, err
	}
	return bytes.Equal(leftBytes, rightBytes), nil
}

func generate() ([]byte, error) {
	g := newGenerator()
	var body bytes.Buffer
	body.WriteString("// DO NOT EDIT — generated by tools/telemetry-contract-gen from internal/telemetry/projection/{overlay,overlayv2,engineer,strategy,analysis}, internal/telemetry/schema/envelope, and internal/app/telemetrytransport; regenerate with `task telemetry:contract`.\n\n")
	body.WriteString("export type JSONValue = null | boolean | number | string | JSONValue[] | { [key: string]: JSONValue };\n")
	body.WriteString("export type JSONObject = { [key: string]: JSONValue };\n\n")

	for _, enum := range g.sortedEnums() {
		fmt.Fprintf(&body, "export type %s = %s;\n", enum.name, quotedUnion(enum.values))
	}
	body.WriteString("\n")
	if err := g.writeTelemetryField(&body); err != nil {
		return nil, err
	}
	body.WriteString("\n")
	if err := g.writeOverlayQValue(&body); err != nil {
		return nil, err
	}
	body.WriteString("\n")

	for len(g.structs) > 0 {
		roots := g.sortedStructs()
		g.structs = make(map[reflect.Type]structRoot)
		for _, root := range roots {
			if err := g.writeInterface(&body, root); err != nil {
				return nil, err
			}
			body.WriteString("\n")
		}
	}

	// EventFact remains a reserved Go wire kind after F4. This compatibility
	// envelope keeps the existing frontend API compiling until F7 owns facts.
	body.WriteString("/** @deprecated Reserved for the F7 Engineer facts port; no live fact transport exists in F5. */\n")
	body.WriteString("export interface FactEnvelope {\n")
	body.WriteString("  readonly capturedAt: string;\n")
	body.WriteString("  readonly epoch: number;\n")
	body.WriteString("  readonly factSequence: number;\n")
	body.WriteString("  readonly payload: JSONObject;\n")
	body.WriteString("  readonly product: ProductID;\n")
	body.WriteString("  readonly projectionVersion: number;\n")
	body.WriteString("  readonly sequence: number;\n")
	body.WriteString("  readonly statusRevision: number;\n")
	body.WriteString("}\n\n")
	body.WriteString("export type TransportEvent =\n")
	body.WriteString("  | { readonly kind: \"projection\"; readonly value: ProjectionEnvelope }\n")
	body.WriteString("  | { readonly kind: \"status\"; readonly value: StatusEnvelope }\n")
	body.WriteString("  | { readonly kind: \"fact\"; readonly value: FactEnvelope };\n")

	return body.Bytes(), nil
}

func newGenerator() *generator {
	g := &generator{
		names:   make(map[reflect.Type]string),
		structs: make(map[reflect.Type]structRoot),
		enums:   make(map[reflect.Type]enumRoot),
		fieldTypes: map[string]string{
			"StatusEnvelope.payload": "StatusPayload",
			"StatusPayload.state":    "StatusState",
		},
		reserved: make(map[string]reflect.Type),
	}

	g.addEnum(reflect.TypeFor[projection.Provenance](), "TelemetryProvenance", []string{
		string(projection.ProvenanceUnknown), string(projection.ProvenanceObserved),
		string(projection.ProvenanceDerived), string(projection.ProvenanceEstimated),
	})
	g.addEnum(reflect.TypeFor[projection.Freshness](), "TelemetryFreshness", []string{
		string(projection.FreshnessMissing), string(projection.FreshnessFresh),
		string(projection.FreshnessStale), string(projection.FreshnessInvalid),
	})
	g.addEnum(reflect.TypeFor[overlay.Capability](), "OverlayCapability", []string{
		string(overlay.CapabilitySession), string(overlay.CapabilityStandings),
		string(overlay.CapabilityControls), string(overlay.CapabilityHistory),
		string(overlay.CapabilityPit), string(overlay.CapabilitySpatial),
	})
	g.addEnum(reflect.TypeFor[overlayv2.Quality](), "OverlayQualityV2", []string{
		string(overlayv2.QualityFresh), string(overlayv2.QualityStale),
		string(overlayv2.QualityMissing), string(overlayv2.QualityInvalid),
	})
	g.addEnum(reflect.TypeFor[overlayv2.Authority](), "OverlayAuthorityV2", []string{
		string(overlayv2.AuthorityNative), string(overlayv2.AuthorityDerived), string(overlayv2.AuthorityEstimated),
	})
	g.addEnum(reflect.TypeFor[overlayv2.Mode](), "OverlayModeV2", []string{
		string(overlayv2.ModeNone), string(overlayv2.ModeOfficial),
		string(overlayv2.ModeReconstructed), string(overlayv2.ModeEstimated),
	})
	g.addEnum(reflect.TypeFor[overlayv2.SpeedUnit](), "OverlaySpeedUnitV2", []string{
		string(overlayv2.SpeedUnitMPS), string(overlayv2.SpeedUnitKPH), string(overlayv2.SpeedUnitMPH),
	})
	g.addEnum(reflect.TypeFor[overlayv2.TemperatureUnit](), "OverlayTemperatureUnitV2", []string{
		string(overlayv2.TemperatureUnitCelsius), string(overlayv2.TemperatureUnitFahrenheit),
	})
	g.addEnum(reflect.TypeFor[overlayv2.PressureUnit](), "OverlayPressureUnitV2", []string{
		string(overlayv2.PressureUnitKPA), string(overlayv2.PressureUnitPSI),
	})
	g.addEnum(reflect.TypeFor[overlayv2.FuelUnit](), "OverlayFuelUnitV2", []string{
		string(overlayv2.FuelUnitLiters), string(overlayv2.FuelUnitGallonsUS),
	})
	g.addEnum(reflect.TypeFor[engineer.CapabilityGroup](), "EngineerCapability", []string{
		string(engineer.GroupSession), string(engineer.GroupStandings),
		string(engineer.GroupControls), string(engineer.GroupPit), string(engineer.GroupFuel),
		string(engineer.GroupGaps), string(engineer.GroupSpatial),
	})
	g.addEnum(reflect.TypeFor[engineer.FactKind](), "EngineerFactKind", []string{
		string(engineer.FactSessionStarted), string(engineer.FactSessionEnded),
		string(engineer.FactLapCompleted), string(engineer.FactPitEntered),
		string(engineer.FactPitExited), string(engineer.FactDriverChanged),
		string(engineer.FactConnectionLost), string(engineer.FactConnectionRecovered),
	})
	g.addEnum(reflect.TypeFor[engineer.SourceState](), "StatusState", []string{
		string(engineer.SourceStopped), string(engineer.SourceDetecting),
		string(engineer.SourceConnecting), string(engineer.SourceLive),
		string(engineer.SourceDegraded), string(engineer.SourceStale),
		string(engineer.SourceError), string(engineer.SourceStopping),
	})
	g.addEnum(reflect.TypeFor[strategy.Capability](), "StrategyCapability", []string{
		string(strategy.CapabilitySession), string(strategy.CapabilityProgress),
		string(strategy.CapabilityPit), string(strategy.CapabilityFuel),
	})
	g.addEnum(reflect.TypeFor[analysis.Capability](), "AnalysisCapability", []string{
		string(analysis.CapabilitySession), string(analysis.CapabilityLap),
		string(analysis.CapabilityControls),
	})
	g.addEnum(reflect.TypeFor[telemetrytransport.ProductID](), "ProductID", []string{
		string(telemetrytransport.ProductOverlay), string(telemetrytransport.ProductEngineer),
		string(telemetrytransport.ProductStrategy), string(telemetrytransport.ProductAnalysis),
	})
	g.addEnum(reflect.TypeFor[telemetrytransport.SnapshotKind](), "SnapshotKind", []string{
		string(telemetrytransport.Full),
	})
	g.addEnum(reflect.TypeFor[telemetrytransport.EventKind](), "EventKind", []string{
		string(telemetrytransport.EventSnapshot), string(telemetrytransport.EventStatus),
		string(telemetrytransport.EventFact),
	})

	g.addStruct(reflect.TypeFor[projection.Metadata](), "TelemetryMetadata")
	g.addStruct(reflect.TypeFor[overlay.GroundPositionV1](), "OverlayGroundPositionV1")
	g.addStruct(reflect.TypeFor[overlay.SnapshotV1](), "OverlaySnapshotV1")
	g.addStruct(reflect.TypeFor[overlay.PayloadV1](), "OverlayPayloadV1")
	g.addStruct(reflect.TypeFor[overlay.VehicleV1](), "OverlayVehicleV1")
	g.addStruct(reflect.TypeFor[overlay.ControlHistoryV1](), "OverlayControlHistoryV1")
	g.addStruct(reflect.TypeFor[overlay.ControlSampleV1](), "OverlayControlSampleV1")
	g.addStruct(reflect.TypeFor[overlay.DeltaHistoryV1](), "OverlayDeltaHistoryV1")
	g.addStruct(reflect.TypeFor[overlay.DeltaSampleV1](), "OverlayDeltaSampleV1")
	g.addStruct(reflect.TypeFor[overlayv2.UpdateV2](), "OverlayUpdateV2")
	g.addStruct(reflect.TypeFor[overlayv2.SourceStatusV2](), "OverlaySourceStatusV2")
	g.addStruct(reflect.TypeFor[overlayv2.FrameV2](), "OverlayFrameV2")
	g.addStruct(reflect.TypeFor[overlayv2.UnitsV2](), "OverlayUnitsV2")
	g.addStruct(reflect.TypeFor[overlayv2.SessionV2](), "OverlaySessionV2")
	g.addStruct(reflect.TypeFor[overlayv2.PlayerInstrumentsV2](), "OverlayPlayerInstrumentsV2")
	g.addStruct(reflect.TypeFor[overlayv2.StandingRowV2](), "OverlayStandingRowV2")
	g.addStruct(reflect.TypeFor[overlayv2.RelativeRowV2](), "OverlayRelativeRowV2")
	g.addStruct(reflect.TypeFor[overlayv2.DeltaViewV2](), "OverlayDeltaViewV2")
	g.addStruct(reflect.TypeFor[overlayv2.FuelViewV2](), "OverlayFuelViewV2")
	g.addStruct(reflect.TypeFor[overlayv2.SpotterViewV2](), "OverlaySpotterViewV2")
	g.addStruct(reflect.TypeFor[overlayv2.CapabilityModesV2](), "OverlayCapabilityModesV2")
	g.addStruct(reflect.TypeFor[overlayv2.CapabilitiesV2](), "OverlayCapabilitiesV2")
	g.addStruct(reflect.TypeFor[engineer.SnapshotV1](), "EngineerSnapshotV1")
	g.addStruct(reflect.TypeFor[engineer.PayloadV1](), "EngineerPayloadV1")
	g.addStruct(reflect.TypeFor[engineer.PlayerV1](), "EngineerPlayerV1")
	g.addStruct(reflect.TypeFor[engineer.FactEnvelopeV1](), "EngineerFactEnvelopeV1")
	g.addStruct(reflect.TypeFor[engineer.FactV1](), "EngineerFactV1")
	g.addStruct(reflect.TypeFor[strategy.SnapshotV1](), "StrategySnapshotV1")
	g.addStruct(reflect.TypeFor[strategy.PayloadV1](), "StrategyPayloadV1")
	g.addStruct(reflect.TypeFor[strategy.PlayerV1](), "StrategyPlayerV1")
	g.addStruct(reflect.TypeFor[analysis.SnapshotV1](), "AnalysisSnapshotV1")
	g.addStruct(reflect.TypeFor[analysis.PayloadV1](), "AnalysisPayloadV1")
	g.addStruct(reflect.TypeFor[analysis.PlayerV1](), "AnalysisPlayerV1")
	g.addStruct(reflect.TypeFor[telemetrytransport.Envelope](), "ProjectionEnvelope")
	g.addStruct(reflect.TypeFor[telemetrytransport.StatusPayload](), "StatusPayload")
	g.addStruct(reflect.TypeFor[telemetrytransport.StatusEnvelope](), "StatusEnvelope")

	return g
}

func (g *generator) writeTelemetryField(output *bytes.Buffer) error {
	fields, err := g.jsonFields(reflect.TypeFor[projection.Field[string]]())
	if err != nil {
		return fmt.Errorf("generate TelemetryField: %w", err)
	}
	output.WriteString("export interface TelemetryField<T> {\n")
	for _, field := range fields {
		typeName := "T"
		if field.name != "value" {
			typeName, err = g.typeScriptType(field.typeOf)
			if err != nil {
				return fmt.Errorf("generate TelemetryField.%s: %w", field.name, err)
			}
		}
		fmt.Fprintf(output, "  readonly %s: %s;\n", field.name, typeName)
	}
	output.WriteString("}\n")
	return nil
}

func (g *generator) writeOverlayQValue(output *bytes.Buffer) error {
	fields, err := g.jsonFields(reflect.TypeFor[overlayv2.QValue[string]]())
	if err != nil {
		return fmt.Errorf("generate OverlayQValue: %w", err)
	}
	output.WriteString("export interface OverlayQValue<T> {\n")
	for _, field := range fields {
		typeName := "T"
		if field.name != "v" {
			typeName, err = g.typeScriptType(field.typeOf)
			if err != nil {
				return fmt.Errorf("generate OverlayQValue.%s: %w", field.name, err)
			}
		}
		optional := ""
		if field.optional {
			optional = "?"
			typeName += " | undefined"
		}
		fmt.Fprintf(output, "  readonly %s%s: %s;\n", field.name, optional, typeName)
	}
	output.WriteString("}\n")
	return nil
}

func (g *generator) addEnum(typeOf reflect.Type, name string, values []string) {
	sort.Strings(values)
	g.claimName(typeOf, name)
	g.enums[typeOf] = enumRoot{typeOf: typeOf, name: name, values: values}
}

func (g *generator) addStruct(typeOf reflect.Type, name string) {
	g.claimName(typeOf, name)
	g.structs[typeOf] = structRoot{typeOf: typeOf, name: name}
}

func (g *generator) claimName(typeOf reflect.Type, name string) {
	if previous, exists := g.reserved[name]; exists && previous != typeOf {
		panic(fmt.Sprintf("generated TypeScript name %q is shared by %s and %s", name, previous, typeOf))
	}
	g.reserved[name] = typeOf
	g.names[typeOf] = name
}

func (g *generator) writeInterface(output *bytes.Buffer, root structRoot) error {
	fields, err := g.jsonFields(root.typeOf)
	if err != nil {
		return fmt.Errorf("generate %s: %w", root.name, err)
	}
	fmt.Fprintf(output, "export interface %s {\n", root.name)
	for _, field := range fields {
		typeName, err := g.typeScriptType(field.typeOf)
		if err != nil {
			return fmt.Errorf("generate %s.%s: %w", root.name, field.name, err)
		}
		if override := g.fieldTypes[root.name+"."+field.name]; override != "" {
			typeName = override
		}
		if field.pointer {
			typeName += " | null"
		}
		optional := ""
		if field.optional {
			optional = "?"
			typeName += " | undefined"
		}
		fmt.Fprintf(output, "  readonly %s%s: %s;\n", field.name, optional, typeName)
	}
	output.WriteString("}\n")
	return nil
}

type jsonField struct {
	name     string
	typeOf   reflect.Type
	optional bool
	pointer  bool
}

func (g *generator) jsonFields(typeOf reflect.Type) ([]jsonField, error) {
	var fields []jsonField
	for index := 0; index < typeOf.NumField(); index++ {
		field := typeOf.Field(index)
		if !field.IsExported() {
			continue
		}
		tag := field.Tag.Get("json")
		parts := strings.Split(tag, ",")
		if parts[0] == "-" {
			continue
		}
		if field.Anonymous && parts[0] == "" {
			embedded := field.Type
			if embedded.Kind() == reflect.Pointer {
				embedded = embedded.Elem()
			}
			if embedded.Kind() != reflect.Struct {
				return nil, fmt.Errorf("embedded field %s is not a struct", field.Name)
			}
			nested, err := g.jsonFields(embedded)
			if err != nil {
				return nil, err
			}
			fields = append(fields, nested...)
			continue
		}
		name := parts[0]
		if name == "" {
			name = field.Name
		}
		optional := false
		for _, option := range parts[1:] {
			optional = optional || option == "omitempty"
		}
		fieldType := field.Type
		pointer := fieldType.Kind() == reflect.Pointer
		if pointer {
			fieldType = fieldType.Elem()
		}
		fields = append(fields, jsonField{name: name, typeOf: fieldType, optional: optional, pointer: pointer})
	}
	sort.Slice(fields, func(left, right int) bool { return fields[left].name < fields[right].name })
	return fields, nil
}

func (g *generator) typeScriptType(typeOf reflect.Type) (string, error) {
	if typeOf == rawMessageType {
		return "JSONObject", nil
	}
	if name := g.names[typeOf]; name != "" {
		return name, nil
	}
	if typeOf.PkgPath() == reflect.TypeFor[projection.Field[string]]().PkgPath() && strings.HasPrefix(typeOf.Name(), "Field[") {
		valueType, ok := typeOf.FieldByName("Value")
		if !ok {
			return "", fmt.Errorf("projection field %s has no Value", typeOf)
		}
		value, err := g.typeScriptType(valueType.Type)
		if err != nil {
			return "", err
		}
		return "TelemetryField<" + value + ">", nil
	}
	if typeOf.PkgPath() == reflect.TypeFor[overlayv2.QValue[string]]().PkgPath() && strings.HasPrefix(typeOf.Name(), "QValue[") {
		valueType, ok := typeOf.FieldByName("V")
		if !ok {
			return "", fmt.Errorf("overlay QValue %s has no V", typeOf)
		}
		value, err := g.typeScriptType(valueType.Type)
		if err != nil {
			return "", err
		}
		return "OverlayQValue<" + value + ">", nil
	}

	switch typeOf.Kind() {
	case reflect.Bool:
		return "boolean", nil
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number", nil
	case reflect.String:
		return "string", nil
	case reflect.Slice, reflect.Array:
		element, err := g.typeScriptType(typeOf.Elem())
		if err != nil {
			return "", err
		}
		return "readonly " + element + "[]", nil
	case reflect.Map:
		if typeOf.Key().Kind() != reflect.String {
			return "", fmt.Errorf("map key %s is not a string", typeOf.Key())
		}
		value, err := g.typeScriptType(typeOf.Elem())
		if err != nil {
			return "", err
		}
		return "{ readonly [key: string]: " + value + " }", nil
	case reflect.Interface:
		return "unknown", nil
	case reflect.Struct:
		name := g.reachableName(typeOf)
		g.addStruct(typeOf, name)
		return name, nil
	default:
		return "", fmt.Errorf("unsupported Go type %s", typeOf)
	}
}

func (g *generator) reachableName(typeOf reflect.Type) string {
	packageName := filepath.Base(typeOf.PkgPath())
	return exportedIdentifier(packageName) + exportedIdentifier(typeOf.Name())
}

func exportedIdentifier(value string) string {
	words := strings.FieldsFunc(value, func(char rune) bool {
		return char == '-' || char == '_' || char == '.' || char == '/'
	})
	for index, word := range words {
		if word == "" {
			continue
		}
		words[index] = strings.ToUpper(word[:1]) + word[1:]
	}
	return strings.Join(words, "")
}

func (g *generator) sortedEnums() []enumRoot {
	result := make([]enumRoot, 0, len(g.enums))
	for _, root := range g.enums {
		result = append(result, root)
	}
	sort.Slice(result, func(left, right int) bool { return result[left].name < result[right].name })
	return result
}

func (g *generator) sortedStructs() []structRoot {
	result := make([]structRoot, 0, len(g.structs))
	for _, root := range g.structs {
		result = append(result, root)
	}
	sort.Slice(result, func(left, right int) bool { return result[left].name < result[right].name })
	return result
}

func quotedUnion(values []string) string {
	quoted := make([]string, len(values))
	for index, value := range values {
		quoted[index] = fmt.Sprintf("%q", value)
	}
	return strings.Join(quoted, " | ")
}
