//! SVG extraídos del sprite productivo; embebidos para no depender del cwd.
use gpui::{AssetSource, SharedString};
use std::borrow::Cow;

pub struct Icons;

const ASSETS: &[(&str, &[u8])] = &[
    (
        "brand/wordmark.svg",
        include_bytes!("../../../../build/brand/wordmark/vantare-wordmark-blanco.svg"),
    ),
    (
        "icons/alert.svg",
        include_bytes!("../../assets/pit/alert.svg"),
    ),
    (
        "icons/bell.svg",
        include_bytes!("../../assets/pit/bell.svg"),
    ),
    (
        "icons/check.svg",
        include_bytes!("../../assets/pit/check.svg"),
    ),
    (
        "icons/clock.svg",
        include_bytes!("../../assets/pit/clock.svg"),
    ),
    (
        "icons/down.svg",
        include_bytes!("../../assets/pit/down.svg"),
    ),
    (
        "icons/flag.svg",
        include_bytes!("../../assets/pit/flag.svg"),
    ),
    (
        "icons/flask.svg",
        include_bytes!("../../assets/pit/flask.svg"),
    ),
    (
        "icons/gamepad.svg",
        include_bytes!("../../assets/pit/gamepad.svg"),
    ),
    (
        "icons/gear.svg",
        include_bytes!("../../assets/pit/gear.svg"),
    ),
    (
        "icons/headset.svg",
        include_bytes!("../../assets/pit/headset.svg"),
    ),
    (
        "icons/home.svg",
        include_bytes!("../../assets/pit/home.svg"),
    ),
    ("icons/key.svg", include_bytes!("../../assets/pit/key.svg")),
    (
        "icons/layers.svg",
        include_bytes!("../../assets/pit/layers.svg"),
    ),
    (
        "icons/lock.svg",
        include_bytes!("../../assets/pit/lock.svg"),
    ),
    (
        "icons/mark.svg",
        include_bytes!("../../assets/pit/mark.svg"),
    ),
    ("icons/max.svg", include_bytes!("../../assets/pit/max.svg")),
    ("icons/min.svg", include_bytes!("../../assets/pit/min.svg")),
    (
        "icons/monitor.svg",
        include_bytes!("../../assets/pit/monitor.svg"),
    ),
    (
        "icons/panel.svg",
        include_bytes!("../../assets/pit/panel.svg"),
    ),
    (
        "icons/pencil.svg",
        include_bytes!("../../assets/pit/pencil.svg"),
    ),
    (
        "icons/play.svg",
        include_bytes!("../../assets/pit/play.svg"),
    ),
    (
        "icons/plus.svg",
        include_bytes!("../../assets/pit/plus.svg"),
    ),
    (
        "icons/pulse.svg",
        include_bytes!("../../assets/pit/pulse.svg"),
    ),
    (
        "icons/refresh.svg",
        include_bytes!("../../assets/pit/refresh.svg"),
    ),
    (
        "icons/right.svg",
        include_bytes!("../../assets/pit/right.svg"),
    ),
    (
        "icons/rocket.svg",
        include_bytes!("../../assets/pit/rocket.svg"),
    ),
    (
        "icons/route.svg",
        include_bytes!("../../assets/pit/route.svg"),
    ),
    (
        "icons/search.svg",
        include_bytes!("../../assets/pit/search.svg"),
    ),
    (
        "icons/star.svg",
        include_bytes!("../../assets/pit/star.svg"),
    ),
    (
        "icons/track.svg",
        include_bytes!("../../assets/pit/track.svg"),
    ),
    (
        "icons/v-bell.svg",
        include_bytes!("../../assets/pit/v-bell.svg"),
    ),
    (
        "icons/v-calendar.svg",
        include_bytes!("../../assets/pit/v-calendar.svg"),
    ),
    (
        "icons/v-camera.svg",
        include_bytes!("../../assets/pit/v-camera.svg"),
    ),
    (
        "icons/v-chat.svg",
        include_bytes!("../../assets/pit/v-chat.svg"),
    ),
    (
        "icons/v-download.svg",
        include_bytes!("../../assets/pit/v-download.svg"),
    ),
    (
        "icons/v-engineer.svg",
        include_bytes!("../../assets/pit/v-engineer.svg"),
    ),
    (
        "icons/v-gauge.svg",
        include_bytes!("../../assets/pit/v-gauge.svg"),
    ),
    (
        "icons/v-helmet.svg",
        include_bytes!("../../assets/pit/v-helmet.svg"),
    ),
    (
        "icons/v-home.svg",
        include_bytes!("../../assets/pit/v-home.svg"),
    ),
    (
        "icons/v-keys.svg",
        include_bytes!("../../assets/pit/v-keys.svg"),
    ),
    (
        "icons/v-launch.svg",
        include_bytes!("../../assets/pit/v-launch.svg"),
    ),
    (
        "icons/v-lock.svg",
        include_bytes!("../../assets/pit/v-lock.svg"),
    ),
    (
        "icons/v-monitor.svg",
        include_bytes!("../../assets/pit/v-monitor.svg"),
    ),
    (
        "icons/v-music.svg",
        include_bytes!("../../assets/pit/v-music.svg"),
    ),
    (
        "icons/v-palette.svg",
        include_bytes!("../../assets/pit/v-palette.svg"),
    ),
    (
        "icons/v-rec.svg",
        include_bytes!("../../assets/pit/v-rec.svg"),
    ),
    (
        "icons/v-roadmap.svg",
        include_bytes!("../../assets/pit/v-roadmap.svg"),
    ),
    (
        "icons/v-shield.svg",
        include_bytes!("../../assets/pit/v-shield.svg"),
    ),
    (
        "icons/v-side.svg",
        include_bytes!("../../assets/pit/v-side.svg"),
    ),
    (
        "icons/v-sliders.svg",
        include_bytes!("../../assets/pit/v-sliders.svg"),
    ),
    (
        "icons/v-strategy.svg",
        include_bytes!("../../assets/pit/v-strategy.svg"),
    ),
    (
        "icons/v-studio.svg",
        include_bytes!("../../assets/pit/v-studio.svg"),
    ),
    (
        "icons/v-testing.svg",
        include_bytes!("../../assets/pit/v-testing.svg"),
    ),
    (
        "icons/v-wheel.svg",
        include_bytes!("../../assets/pit/v-wheel.svg"),
    ),
    ("icons/x.svg", include_bytes!("../../assets/pit/x.svg")),
    (
        "icons/i-vantare.svg",
        include_bytes!("../../assets/icons/i-vantare.svg"),
    ),
    (
        "icons/i-inicio.svg",
        include_bytes!("../../assets/icons/i-inicio.svg"),
    ),
    (
        "icons/i-studio.svg",
        include_bytes!("../../assets/icons/i-studio.svg"),
    ),
    (
        "icons/i-launcher.svg",
        include_bytes!("../../assets/icons/i-launcher.svg"),
    ),
    (
        "icons/i-carreras.svg",
        include_bytes!("../../assets/icons/i-carreras.svg"),
    ),
    (
        "icons/i-estrategia.svg",
        include_bytes!("../../assets/icons/i-estrategia.svg"),
    ),
    (
        "icons/i-ingeniero.svg",
        include_bytes!("../../assets/icons/i-ingeniero.svg"),
    ),
    (
        "icons/i-telemetria.svg",
        include_bytes!("../../assets/icons/i-telemetria.svg"),
    ),
    (
        "icons/i-roadmap.svg",
        include_bytes!("../../assets/icons/i-roadmap.svg"),
    ),
    (
        "icons/i-ajustes.svg",
        include_bytes!("../../assets/icons/i-ajustes.svg"),
    ),
    (
        "icons/i-cuenta.svg",
        include_bytes!("../../assets/icons/i-cuenta.svg"),
    ),
    (
        "icons/i-comando.svg",
        include_bytes!("../../assets/icons/i-comando.svg"),
    ),
    (
        "icons/i-panel.svg",
        include_bytes!("../../assets/icons/i-panel.svg"),
    ),
    (
        "icons/i-flask.svg",
        include_bytes!("../../assets/icons/i-flask.svg"),
    ),
    (
        "icons/i-lock.svg",
        include_bytes!("../../assets/icons/i-lock.svg"),
    ),
    (
        "icons/i-campana.svg",
        include_bytes!("../../assets/icons/i-campana.svg"),
    ),
    (
        "icons/i-chevron.svg",
        include_bytes!("../../assets/icons/i-chevron.svg"),
    ),
];

impl AssetSource for Icons {
    fn load(&self, path: &str) -> gpui::Result<Option<Cow<'static, [u8]>>> {
        Ok(ASSETS
            .iter()
            .find(|(name, _)| *name == path)
            .map(|(_, data)| Cow::Borrowed(*data)))
    }
    fn list(&self, path: &str) -> gpui::Result<Vec<SharedString>> {
        Ok(ASSETS
            .iter()
            .filter(|(name, _)| name.starts_with(path))
            .map(|(name, _)| (*name).into())
            .collect())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn all_shell_icons_are_embedded_and_unknown_paths_are_rejected() {
        for section in crate::Section::ALL {
            let path = format!("icons/{}.svg", super::super::navigation::icon(*section));
            assert!(Icons.load(&path).expect("asset").is_some());
        }
        assert!(Icons.load("../secret.svg").expect("asset").is_none());
        assert!(
            Icons
                .load("brand/wordmark.svg")
                .expect("wordmark")
                .is_some()
        );
        assert_eq!(Icons.list("brand/").expect("brand list").len(), 1);
        assert_eq!(Icons.list("icons/").expect("list").len(), ASSETS.len() - 1);
    }
}
